// Code generated by protoc-gen-go. DO NOT EDIT.
// source: provider/proto/provider.proto

package go_micro_srv_provider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PlanInterval int32

const (
	PlanInterval_UNKNOWN PlanInterval = 0
	PlanInterval_DAY     PlanInterval = 1
	PlanInterval_WEEK    PlanInterval = 2
	PlanInterval_MONTH   PlanInterval = 3
	PlanInterval_YEAR    PlanInterval = 4
)

var PlanInterval_name = map[int32]string{
	0: "UNKNOWN",
	1: "DAY",
	2: "WEEK",
	3: "MONTH",
	4: "YEAR",
}

var PlanInterval_value = map[string]int32{
	"UNKNOWN": 0,
	"DAY":     1,
	"WEEK":    2,
	"MONTH":   3,
	"YEAR":    4,
}

func (x PlanInterval) String() string {
	return proto.EnumName(PlanInterval_name, int32(x))
}

func (PlanInterval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{0}
}

type Product struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type CreateProductRequest struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductRequest) Reset()         { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()    {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{1}
}

func (m *CreateProductRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductRequest.Unmarshal(m, b)
}
func (m *CreateProductRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductRequest.Marshal(b, m, deterministic)
}
func (m *CreateProductRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductRequest.Merge(m, src)
}
func (m *CreateProductRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProductRequest.Size(m)
}
func (m *CreateProductRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductRequest proto.InternalMessageInfo

func (m *CreateProductRequest) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProductResponse) Reset()         { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()    {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{2}
}

func (m *CreateProductResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProductResponse.Unmarshal(m, b)
}
func (m *CreateProductResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProductResponse.Marshal(b, m, deterministic)
}
func (m *CreateProductResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProductResponse.Merge(m, src)
}
func (m *CreateProductResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProductResponse.Size(m)
}
func (m *CreateProductResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProductResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProductResponse proto.InternalMessageInfo

type Plan struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               int64        `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string       `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Interval             PlanInterval `protobuf:"varint,5,opt,name=interval,proto3,enum=go.micro.srv.provider.PlanInterval" json:"interval,omitempty"`
	ProductId            string       `protobuf:"bytes,6,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{3}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Plan) GetInterval() PlanInterval {
	if m != nil {
		return m.Interval
	}
	return PlanInterval_UNKNOWN
}

func (m *Plan) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type CreatePlanRequest struct {
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanRequest) Reset()         { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()    {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{4}
}

func (m *CreatePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRequest.Unmarshal(m, b)
}
func (m *CreatePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRequest.Marshal(b, m, deterministic)
}
func (m *CreatePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRequest.Merge(m, src)
}
func (m *CreatePlanRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRequest.Size(m)
}
func (m *CreatePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRequest proto.InternalMessageInfo

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type CreatePlanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanResponse) Reset()         { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()    {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{5}
}

func (m *CreatePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanResponse.Unmarshal(m, b)
}
func (m *CreatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanResponse.Marshal(b, m, deterministic)
}
func (m *CreatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanResponse.Merge(m, src)
}
func (m *CreatePlanResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlanResponse.Size(m)
}
func (m *CreatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanResponse proto.InternalMessageInfo

type Customer struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{6}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Customer) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Customer) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type CreateCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{7}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{8}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

type CreateSubscriptionRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,2,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	PlanId               string   `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{9}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

func (m *CreateSubscriptionRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *CreateSubscriptionRequest) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{10}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

type ListSubscriptionsRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,2,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	PlanId               string   `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscriptionsRequest) Reset()         { *m = ListSubscriptionsRequest{} }
func (m *ListSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsRequest) ProtoMessage()    {}
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{11}
}

func (m *ListSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsRequest.Unmarshal(m, b)
}
func (m *ListSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsRequest.Merge(m, src)
}
func (m *ListSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsRequest.Size(m)
}
func (m *ListSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsRequest proto.InternalMessageInfo

func (m *ListSubscriptionsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *ListSubscriptionsRequest) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *ListSubscriptionsRequest) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type Subscription struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan                 *Plan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Product              *Product `protobuf:"bytes,3,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{12}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Subscription) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type ListSubscriptionsResponse struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubscriptionsResponse) Reset()         { *m = ListSubscriptionsResponse{} }
func (m *ListSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsResponse) ProtoMessage()    {}
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{13}
}

func (m *ListSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsResponse.Merge(m, src)
}
func (m *ListSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsResponse.Size(m)
}
func (m *ListSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsResponse proto.InternalMessageInfo

func (m *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	CustomerId           string   `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,4,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CardBrand            string   `protobuf:"bytes,6,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardExpMonth         string   `protobuf:"bytes,7,opt,name=card_exp_month,json=cardExpMonth,proto3" json:"card_exp_month,omitempty"`
	CardExpYear          string   `protobuf:"bytes,8,opt,name=card_exp_year,json=cardExpYear,proto3" json:"card_exp_year,omitempty"`
	CardLast_4           string   `protobuf:"bytes,9,opt,name=card_last_4,json=cardLast4,proto3" json:"card_last_4,omitempty"`
	Default              bool     `protobuf:"varint,10,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{14}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentMethod) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *PaymentMethod) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *PaymentMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentMethod) GetCardBrand() string {
	if m != nil {
		return m.CardBrand
	}
	return ""
}

func (m *PaymentMethod) GetCardExpMonth() string {
	if m != nil {
		return m.CardExpMonth
	}
	return ""
}

func (m *PaymentMethod) GetCardExpYear() string {
	if m != nil {
		return m.CardExpYear
	}
	return ""
}

func (m *PaymentMethod) GetCardLast_4() string {
	if m != nil {
		return m.CardLast_4
	}
	return ""
}

func (m *PaymentMethod) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type CreatePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,3,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentMethodRequest) Reset()         { *m = CreatePaymentMethodRequest{} }
func (m *CreatePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodRequest) ProtoMessage()    {}
func (*CreatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{15}
}

func (m *CreatePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodRequest.Unmarshal(m, b)
}
func (m *CreatePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodRequest.Merge(m, src)
}
func (m *CreatePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodRequest.Size(m)
}
func (m *CreatePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodRequest proto.InternalMessageInfo

func (m *CreatePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreatePaymentMethodRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *CreatePaymentMethodRequest) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

type ListPaymentMethodsRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,2,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPaymentMethodsRequest) Reset()         { *m = ListPaymentMethodsRequest{} }
func (m *ListPaymentMethodsRequest) String() string { return proto.CompactTextString(m) }
func (*ListPaymentMethodsRequest) ProtoMessage()    {}
func (*ListPaymentMethodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{16}
}

func (m *ListPaymentMethodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentMethodsRequest.Unmarshal(m, b)
}
func (m *ListPaymentMethodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentMethodsRequest.Marshal(b, m, deterministic)
}
func (m *ListPaymentMethodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentMethodsRequest.Merge(m, src)
}
func (m *ListPaymentMethodsRequest) XXX_Size() int {
	return xxx_messageInfo_ListPaymentMethodsRequest.Size(m)
}
func (m *ListPaymentMethodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentMethodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentMethodsRequest proto.InternalMessageInfo

func (m *ListPaymentMethodsRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *ListPaymentMethodsRequest) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

type DeletePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodRequest) Reset()         { *m = DeletePaymentMethodRequest{} }
func (m *DeletePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodRequest) ProtoMessage()    {}
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{17}
}

func (m *DeletePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodRequest.Unmarshal(m, b)
}
func (m *DeletePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodRequest.Merge(m, src)
}
func (m *DeletePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodRequest.Size(m)
}
func (m *DeletePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodRequest proto.InternalMessageInfo

func (m *DeletePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreatePaymentMethodResponse struct {
	PaymentMethod        *PaymentMethod `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreatePaymentMethodResponse) Reset()         { *m = CreatePaymentMethodResponse{} }
func (m *CreatePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodResponse) ProtoMessage()    {}
func (*CreatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{18}
}

func (m *CreatePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodResponse.Unmarshal(m, b)
}
func (m *CreatePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodResponse.Merge(m, src)
}
func (m *CreatePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodResponse.Size(m)
}
func (m *CreatePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodResponse proto.InternalMessageInfo

func (m *CreatePaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

type ListPaymentMethodsResponse struct {
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,1,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListPaymentMethodsResponse) Reset()         { *m = ListPaymentMethodsResponse{} }
func (m *ListPaymentMethodsResponse) String() string { return proto.CompactTextString(m) }
func (*ListPaymentMethodsResponse) ProtoMessage()    {}
func (*ListPaymentMethodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{19}
}

func (m *ListPaymentMethodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPaymentMethodsResponse.Unmarshal(m, b)
}
func (m *ListPaymentMethodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPaymentMethodsResponse.Marshal(b, m, deterministic)
}
func (m *ListPaymentMethodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPaymentMethodsResponse.Merge(m, src)
}
func (m *ListPaymentMethodsResponse) XXX_Size() int {
	return xxx_messageInfo_ListPaymentMethodsResponse.Size(m)
}
func (m *ListPaymentMethodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPaymentMethodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPaymentMethodsResponse proto.InternalMessageInfo

func (m *ListPaymentMethodsResponse) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

type DeletePaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodResponse) Reset()         { *m = DeletePaymentMethodResponse{} }
func (m *DeletePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodResponse) ProtoMessage()    {}
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{20}
}

func (m *DeletePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodResponse.Unmarshal(m, b)
}
func (m *DeletePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodResponse.Merge(m, src)
}
func (m *DeletePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodResponse.Size(m)
}
func (m *DeletePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodResponse proto.InternalMessageInfo

type SetDefaultPaymentMethodRequest struct {
	CustomerId           string   `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerType         string   `protobuf:"bytes,2,opt,name=customer_type,json=customerType,proto3" json:"customer_type,omitempty"`
	PaymentMethodId      string   `protobuf:"bytes,3,opt,name=payment_method_id,json=paymentMethodId,proto3" json:"payment_method_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDefaultPaymentMethodRequest) Reset()         { *m = SetDefaultPaymentMethodRequest{} }
func (m *SetDefaultPaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*SetDefaultPaymentMethodRequest) ProtoMessage()    {}
func (*SetDefaultPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{21}
}

func (m *SetDefaultPaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDefaultPaymentMethodRequest.Unmarshal(m, b)
}
func (m *SetDefaultPaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDefaultPaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *SetDefaultPaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDefaultPaymentMethodRequest.Merge(m, src)
}
func (m *SetDefaultPaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_SetDefaultPaymentMethodRequest.Size(m)
}
func (m *SetDefaultPaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDefaultPaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDefaultPaymentMethodRequest proto.InternalMessageInfo

func (m *SetDefaultPaymentMethodRequest) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *SetDefaultPaymentMethodRequest) GetCustomerType() string {
	if m != nil {
		return m.CustomerType
	}
	return ""
}

func (m *SetDefaultPaymentMethodRequest) GetPaymentMethodId() string {
	if m != nil {
		return m.PaymentMethodId
	}
	return ""
}

type SetDefaultPaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDefaultPaymentMethodResponse) Reset()         { *m = SetDefaultPaymentMethodResponse{} }
func (m *SetDefaultPaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*SetDefaultPaymentMethodResponse) ProtoMessage()    {}
func (*SetDefaultPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{22}
}

func (m *SetDefaultPaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDefaultPaymentMethodResponse.Unmarshal(m, b)
}
func (m *SetDefaultPaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDefaultPaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *SetDefaultPaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDefaultPaymentMethodResponse.Merge(m, src)
}
func (m *SetDefaultPaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_SetDefaultPaymentMethodResponse.Size(m)
}
func (m *SetDefaultPaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDefaultPaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDefaultPaymentMethodResponse proto.InternalMessageInfo

type ListPlansRequest struct {
	ProductId            string   `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlansRequest) Reset()         { *m = ListPlansRequest{} }
func (m *ListPlansRequest) String() string { return proto.CompactTextString(m) }
func (*ListPlansRequest) ProtoMessage()    {}
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{23}
}

func (m *ListPlansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlansRequest.Unmarshal(m, b)
}
func (m *ListPlansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlansRequest.Marshal(b, m, deterministic)
}
func (m *ListPlansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlansRequest.Merge(m, src)
}
func (m *ListPlansRequest) XXX_Size() int {
	return xxx_messageInfo_ListPlansRequest.Size(m)
}
func (m *ListPlansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlansRequest proto.InternalMessageInfo

func (m *ListPlansRequest) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

type ListPlansResponse struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlansResponse) Reset()         { *m = ListPlansResponse{} }
func (m *ListPlansResponse) String() string { return proto.CompactTextString(m) }
func (*ListPlansResponse) ProtoMessage()    {}
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8de96a1ce041752b, []int{24}
}

func (m *ListPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlansResponse.Unmarshal(m, b)
}
func (m *ListPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlansResponse.Marshal(b, m, deterministic)
}
func (m *ListPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlansResponse.Merge(m, src)
}
func (m *ListPlansResponse) XXX_Size() int {
	return xxx_messageInfo_ListPlansResponse.Size(m)
}
func (m *ListPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlansResponse proto.InternalMessageInfo

func (m *ListPlansResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func init() {
	proto.RegisterEnum("go.micro.srv.provider.PlanInterval", PlanInterval_name, PlanInterval_value)
	proto.RegisterType((*Product)(nil), "go.micro.srv.provider.Product")
	proto.RegisterType((*CreateProductRequest)(nil), "go.micro.srv.provider.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "go.micro.srv.provider.CreateProductResponse")
	proto.RegisterType((*Plan)(nil), "go.micro.srv.provider.Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "go.micro.srv.provider.CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "go.micro.srv.provider.CreatePlanResponse")
	proto.RegisterType((*Customer)(nil), "go.micro.srv.provider.Customer")
	proto.RegisterMapType((map[string]string)(nil), "go.micro.srv.provider.Customer.MetadataEntry")
	proto.RegisterType((*CreateCustomerRequest)(nil), "go.micro.srv.provider.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "go.micro.srv.provider.CreateCustomerResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "go.micro.srv.provider.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "go.micro.srv.provider.CreateSubscriptionResponse")
	proto.RegisterType((*ListSubscriptionsRequest)(nil), "go.micro.srv.provider.ListSubscriptionsRequest")
	proto.RegisterType((*Subscription)(nil), "go.micro.srv.provider.Subscription")
	proto.RegisterType((*ListSubscriptionsResponse)(nil), "go.micro.srv.provider.ListSubscriptionsResponse")
	proto.RegisterType((*PaymentMethod)(nil), "go.micro.srv.provider.PaymentMethod")
	proto.RegisterType((*CreatePaymentMethodRequest)(nil), "go.micro.srv.provider.CreatePaymentMethodRequest")
	proto.RegisterType((*ListPaymentMethodsRequest)(nil), "go.micro.srv.provider.ListPaymentMethodsRequest")
	proto.RegisterType((*DeletePaymentMethodRequest)(nil), "go.micro.srv.provider.DeletePaymentMethodRequest")
	proto.RegisterType((*CreatePaymentMethodResponse)(nil), "go.micro.srv.provider.CreatePaymentMethodResponse")
	proto.RegisterType((*ListPaymentMethodsResponse)(nil), "go.micro.srv.provider.ListPaymentMethodsResponse")
	proto.RegisterType((*DeletePaymentMethodResponse)(nil), "go.micro.srv.provider.DeletePaymentMethodResponse")
	proto.RegisterType((*SetDefaultPaymentMethodRequest)(nil), "go.micro.srv.provider.SetDefaultPaymentMethodRequest")
	proto.RegisterType((*SetDefaultPaymentMethodResponse)(nil), "go.micro.srv.provider.SetDefaultPaymentMethodResponse")
	proto.RegisterType((*ListPlansRequest)(nil), "go.micro.srv.provider.ListPlansRequest")
	proto.RegisterType((*ListPlansResponse)(nil), "go.micro.srv.provider.ListPlansResponse")
}

func init() { proto.RegisterFile("provider/proto/provider.proto", fileDescriptor_8de96a1ce041752b) }

var fileDescriptor_8de96a1ce041752b = []byte{
	// 1067 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x2e, 0x45, 0xd9, 0x92, 0x46, 0x96, 0x22, 0x6f, 0x9d, 0x98, 0xa1, 0x6b, 0x5b, 0x65, 0x02,
	0x54, 0x4d, 0x13, 0x39, 0x56, 0xd3, 0x22, 0x68, 0x0e, 0x45, 0x6a, 0xab, 0xa8, 0xe0, 0xc8, 0x11,
	0x18, 0x17, 0x81, 0x2f, 0x15, 0xd6, 0xe2, 0x26, 0x61, 0xc2, 0xbf, 0x2e, 0x57, 0x42, 0x54, 0xf4,
	0x01, 0xda, 0x6b, 0xef, 0x7d, 0x8d, 0x1c, 0xfb, 0x6c, 0x05, 0xc9, 0x5d, 0x8a, 0x94, 0x49, 0x5a,
	0x06, 0x82, 0xdc, 0x38, 0xb3, 0xf3, 0xfb, 0xcd, 0xec, 0xec, 0x10, 0x76, 0x3d, 0xea, 0xce, 0x4c,
	0x83, 0xd0, 0x03, 0x8f, 0xba, 0xcc, 0x3d, 0x10, 0x64, 0x37, 0x24, 0xd1, 0xcd, 0xd7, 0x6e, 0xd7,
	0x36, 0x27, 0xd4, 0xed, 0xfa, 0x74, 0xd6, 0x15, 0x87, 0xda, 0x6b, 0xa8, 0x8c, 0xa8, 0x6b, 0x4c,
	0x27, 0x0c, 0x35, 0xa1, 0x64, 0x1a, 0x8a, 0xd4, 0x96, 0x3a, 0x35, 0xbd, 0x64, 0x1a, 0x08, 0x41,
	0xd9, 0xc1, 0x36, 0x51, 0x4a, 0x21, 0x27, 0xfc, 0x46, 0x6d, 0xa8, 0x1b, 0xc4, 0x9f, 0x50, 0xd3,
	0x63, 0xa6, 0xeb, 0x28, 0x72, 0x78, 0x94, 0x64, 0xa1, 0x5b, 0xb0, 0x8e, 0x27, 0xcc, 0x9c, 0x11,
	0xa5, 0xdc, 0x96, 0x3a, 0x55, 0x9d, 0x53, 0xda, 0x08, 0xb6, 0x8e, 0x28, 0xc1, 0x8c, 0x70, 0x77,
	0x3a, 0xf9, 0x7d, 0x4a, 0x7c, 0x86, 0x1e, 0x43, 0xc5, 0x8b, 0x38, 0xa1, 0xeb, 0x7a, 0x6f, 0xaf,
	0x9b, 0x19, 0x69, 0x57, 0xe8, 0x09, 0x71, 0x6d, 0x1b, 0x6e, 0x2e, 0x59, 0xf4, 0x3d, 0xd7, 0xf1,
	0x89, 0xf6, 0x9f, 0x04, 0xe5, 0x91, 0x85, 0x9d, 0x95, 0x32, 0x0a, 0xe2, 0xb5, 0xdd, 0xa9, 0xc3,
	0xc2, 0x64, 0x64, 0x9d, 0x53, 0x48, 0x85, 0xea, 0x64, 0x4a, 0x29, 0x71, 0x26, 0xf3, 0x30, 0x93,
	0x9a, 0x1e, 0xd3, 0xe8, 0x47, 0xa8, 0x9a, 0x0e, 0x23, 0x74, 0x86, 0x2d, 0x65, 0xad, 0x2d, 0x75,
	0x9a, 0xbd, 0x3b, 0x79, 0x41, 0x5b, 0xd8, 0x19, 0x70, 0x51, 0x3d, 0x56, 0x42, 0xbb, 0x00, 0x3c,
	0x8b, 0xb1, 0x69, 0x28, 0xeb, 0xa1, 0xf9, 0x1a, 0xe7, 0x0c, 0x0c, 0xed, 0x18, 0x36, 0x79, 0x66,
	0x16, 0x76, 0x04, 0x50, 0x07, 0x50, 0xf6, 0x2c, 0xec, 0x70, 0x94, 0x76, 0x0a, 0x1c, 0xea, 0xa1,
	0xa0, 0xb6, 0x05, 0x28, 0x69, 0x85, 0x83, 0xf3, 0x41, 0x82, 0xea, 0xd1, 0xd4, 0x67, 0xae, 0x4d,
	0x68, 0x16, 0x40, 0x6c, 0xee, 0xc5, 0x00, 0x05, 0xdf, 0x68, 0x00, 0x55, 0x9b, 0x30, 0x6c, 0x60,
	0x86, 0x15, 0xb9, 0x2d, 0x77, 0xea, 0xbd, 0x07, 0x39, 0xbe, 0x85, 0xd9, 0xee, 0x90, 0xcb, 0xf7,
	0x1d, 0x46, 0xe7, 0x7a, 0xac, 0xae, 0x3e, 0x81, 0x46, 0xea, 0x08, 0xb5, 0x40, 0x7e, 0x47, 0xe6,
	0x3c, 0x80, 0xe0, 0x13, 0x6d, 0xc1, 0xda, 0x0c, 0x5b, 0x53, 0x11, 0x42, 0x44, 0xfc, 0x50, 0x7a,
	0x2c, 0x69, 0x67, 0xa2, 0xdc, 0xc2, 0x8d, 0x00, 0xe6, 0x49, 0x50, 0xa9, 0x88, 0xc5, 0xc1, 0xd9,
	0xbf, 0x22, 0x40, 0x3d, 0x56, 0xd0, 0x14, 0xb8, 0xb5, 0x6c, 0x95, 0x03, 0xf5, 0x07, 0xdc, 0x8e,
	0x4e, 0x5e, 0x4c, 0x2f, 0xe2, 0xf6, 0x16, 0x3e, 0xf7, 0xa1, 0x2e, 0x4c, 0x8c, 0x63, 0x04, 0x41,
	0xb0, 0x06, 0x06, 0xba, 0x03, 0x8d, 0x58, 0x20, 0x01, 0xe9, 0x86, 0x60, 0x9e, 0x05, 0xd0, 0x6e,
	0x43, 0x25, 0xa8, 0x54, 0x60, 0x21, 0xba, 0x49, 0xeb, 0x01, 0x39, 0x30, 0xb4, 0x2f, 0x40, 0xcd,
	0xf2, 0xcd, 0x23, 0x9b, 0x83, 0xf2, 0xcc, 0xf4, 0x59, 0xf2, 0xcc, 0xff, 0x44, 0x81, 0xfd, 0x2d,
	0xc1, 0x46, 0xd2, 0xef, 0xa5, 0x0e, 0x12, 0x5d, 0x5a, 0x5a, 0xb1, 0x4b, 0x93, 0xf7, 0x5f, 0xbe,
	0xde, 0xfd, 0x7f, 0x05, 0xb7, 0x33, 0x60, 0x88, 0x30, 0x42, 0x03, 0x68, 0xf8, 0xc9, 0x03, 0x45,
	0x0a, 0x5b, 0x37, 0xef, 0x9e, 0xa6, 0x70, 0x4e, 0x6b, 0x6a, 0x1f, 0x4a, 0xd0, 0x18, 0xe1, 0xb9,
	0x4d, 0x1c, 0x36, 0x24, 0xec, 0x8d, 0x6b, 0x5c, 0x4a, 0x5a, 0x81, 0xca, 0x24, 0x2c, 0x97, 0x11,
	0xe6, 0x2d, 0xeb, 0x82, 0x5c, 0x2e, 0x87, 0x7c, 0x75, 0x39, 0xca, 0x19, 0xe5, 0x10, 0xd7, 0x72,
	0x2d, 0x71, 0x2d, 0x77, 0x01, 0x26, 0x98, 0x1a, 0xe3, 0x0b, 0x8a, 0x9d, 0x78, 0x84, 0x04, 0x9c,
	0x9f, 0x02, 0x06, 0xba, 0x0b, 0xcd, 0xf0, 0x98, 0xbc, 0xf7, 0xc6, 0xb6, 0xeb, 0xb0, 0x37, 0x4a,
	0x85, 0x1b, 0xc6, 0xd4, 0xe8, 0xbf, 0xf7, 0x86, 0x01, 0x0f, 0x69, 0xd0, 0x88, 0xa5, 0xe6, 0x04,
	0x53, 0xa5, 0x1a, 0x0d, 0x74, 0x2e, 0x74, 0x4e, 0x30, 0x45, 0x7b, 0x10, 0x92, 0x63, 0x0b, 0xfb,
	0x6c, 0xfc, 0x48, 0xa9, 0x2d, 0x3c, 0x3d, 0xc3, 0x3e, 0x7b, 0x14, 0x24, 0x6f, 0x90, 0x57, 0x78,
	0x6a, 0x31, 0x05, 0xc2, 0x89, 0x2f, 0x48, 0x8d, 0x8a, 0x2e, 0x4e, 0xa1, 0x27, 0x3a, 0x75, 0x19,
	0xc4, 0x25, 0xa8, 0x4a, 0x57, 0x43, 0x25, 0x5f, 0x86, 0x4a, 0xc3, 0x51, 0x53, 0xa4, 0x3c, 0x7e,
	0xdc, 0xcb, 0xa1, 0xdd, 0x07, 0xf5, 0x98, 0x58, 0x64, 0xb5, 0xb4, 0xb4, 0xb7, 0xb0, 0x93, 0x09,
	0x02, 0xef, 0xd3, 0x13, 0x68, 0x7a, 0xd1, 0xc1, 0xd8, 0x0e, 0x4f, 0xf8, 0x08, 0xbb, 0x9b, 0x77,
	0x0b, 0x52, 0x56, 0x1a, 0x5e, 0x92, 0xd4, 0xde, 0x81, 0x9a, 0x95, 0x3c, 0x77, 0x35, 0x84, 0x1b,
	0x69, 0x57, 0xe2, 0x52, 0xac, 0xe6, 0xab, 0x99, 0xf2, 0xe5, 0x6b, 0xbb, 0xb0, 0x93, 0x09, 0x03,
	0x1f, 0x52, 0xff, 0x48, 0xb0, 0xf7, 0x82, 0xb0, 0xe3, 0xa8, 0x17, 0x32, 0xa1, 0xfa, 0x38, 0xb3,
	0xea, 0x1e, 0x6c, 0xa6, 0xd3, 0x5a, 0x5c, 0xb4, 0x1b, 0xa9, 0x90, 0x07, 0x86, 0xf6, 0x25, 0xec,
	0xe7, 0xc6, 0xc4, 0xe3, 0x3e, 0x84, 0x56, 0x88, 0xa1, 0x85, 0x17, 0x43, 0x35, 0xfd, 0x5c, 0x4b,
	0xcb, 0xcf, 0xf5, 0xcf, 0xb0, 0x99, 0x50, 0xe1, 0x68, 0x1f, 0xc2, 0x5a, 0x30, 0xdf, 0x04, 0xc6,
	0x85, 0x93, 0x30, 0x92, 0xbc, 0x77, 0x04, 0x1b, 0xc9, 0x7d, 0x01, 0xd5, 0xa1, 0xf2, 0xeb, 0xe9,
	0xc9, 0xe9, 0xf3, 0x97, 0xa7, 0xad, 0xcf, 0x50, 0x05, 0xe4, 0xe3, 0xa7, 0xe7, 0x2d, 0x09, 0x55,
	0xa1, 0xfc, 0xb2, 0xdf, 0x3f, 0x69, 0x95, 0x50, 0x0d, 0xd6, 0x86, 0xcf, 0x4f, 0xcf, 0x7e, 0x69,
	0xc9, 0x01, 0xf3, 0xbc, 0xff, 0x54, 0x6f, 0x95, 0x7b, 0xff, 0xd6, 0xa0, 0x3a, 0xe2, 0xd6, 0xd1,
	0x5b, 0x68, 0xa4, 0x56, 0x24, 0xf4, 0x4d, 0xde, 0xcb, 0x98, 0xb1, 0x9a, 0xa9, 0xf7, 0x57, 0x13,
	0xe6, 0x09, 0x63, 0x80, 0xc5, 0xba, 0x81, 0x3a, 0xc5, 0xba, 0x8b, 0xbd, 0x46, 0xfd, 0x7a, 0x05,
	0x49, 0xee, 0xe2, 0x37, 0xa8, 0xc5, 0x40, 0xa3, 0xaf, 0x72, 0xf4, 0x96, 0xab, 0xa7, 0x76, 0xae,
	0x16, 0xe4, 0xf6, 0x6d, 0x68, 0xa6, 0x97, 0x01, 0x54, 0x0c, 0xc1, 0xd2, 0x26, 0xa2, 0x3e, 0x58,
	0x51, 0x9a, 0xbb, 0x9b, 0x8b, 0x05, 0x2d, 0xf5, 0xa2, 0x3e, 0x2c, 0x34, 0x92, 0xb1, 0x8c, 0xa8,
	0x87, 0xd7, 0xd0, 0xe0, 0xae, 0x67, 0x51, 0xcb, 0xa6, 0xde, 0x4e, 0x74, 0x50, 0x00, 0x54, 0xd6,
	0xb2, 0xa1, 0x3e, 0x5c, 0x5d, 0x81, 0xfb, 0xfd, 0x13, 0x3e, 0xcf, 0x98, 0x86, 0xa8, 0x38, 0x83,
	0xac, 0xe1, 0xa1, 0xf6, 0xae, 0xa3, 0xb2, 0x00, 0xfc, 0xf2, 0x7c, 0x44, 0x45, 0x59, 0x64, 0xbe,
	0x23, 0xb9, 0x80, 0x17, 0x0c, 0xdf, 0xbf, 0x24, 0xd8, 0xce, 0x19, 0x3d, 0xe8, 0xbb, 0xbc, 0xa5,
	0xa4, 0x70, 0x7c, 0xaa, 0xdf, 0x5f, 0x57, 0x6d, 0x51, 0x83, 0x8c, 0xc1, 0x9d, 0x5b, 0x83, 0xfc,
	0xb7, 0x2e, 0xb7, 0x06, 0x05, 0xef, 0xc2, 0xc5, 0x7a, 0xf8, 0x3b, 0xfa, 0xed, 0xff, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x70, 0xbc, 0x10, 0xaf, 0x0e, 0x00, 0x00,
}
