// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type RegisterRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Firstname            string   `protobuf:"bytes,3,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,4,opt,name=lastname,proto3" json:"lastname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterRequest) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *RegisterRequest) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

type RegisterResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.service.auth.User")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.service.auth.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.service.auth.LoginResponse")
	proto.RegisterType((*RegisterRequest)(nil), "go.micro.service.auth.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "go.micro.service.auth.RegisterResponse")
}

func init() {
	proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5)
}

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xb5, 0x50, 0x14, 0xc6, 0xef, 0x8d, 0xc6, 0x86, 0x98, 0x48, 0xd6, 0x8b, 0x89, 0x66, 0x4d,
	0xf0, 0x0f, 0xe8, 0x9d, 0x53, 0x13, 0x7e, 0xc0, 0x2a, 0x43, 0xd9, 0x48, 0xbb, 0x75, 0x67, 0xab,
	0x27, 0x7f, 0x91, 0x7f, 0xd2, 0x74, 0x68, 0x29, 0x28, 0x72, 0xf0, 0xd2, 0xe4, 0xcd, 0xbc, 0xbe,
	0x37, 0xef, 0x65, 0xe1, 0x3c, 0x77, 0xd6, 0xdb, 0x7b, 0x5d, 0xf8, 0x19, 0x7f, 0x14, 0x63, 0x71,
	0x9a, 0x58, 0x95, 0x9a, 0x17, 0x67, 0x15, 0xb9, 0x77, 0x55, 0x2e, 0xe4, 0x14, 0xc2, 0x31, 0xa1,
	0x13, 0x47, 0xd0, 0x32, 0x93, 0x28, 0x18, 0x04, 0x37, 0xbd, 0xb8, 0x65, 0x26, 0xe2, 0x12, 0x7a,
	0x53, 0xe3, 0xc8, 0x67, 0x3a, 0xc5, 0xa8, 0xc5, 0xe3, 0x66, 0x20, 0xfa, 0xd0, 0x9d, 0xeb, 0x6a,
	0xd9, 0xe6, 0xe5, 0x12, 0x8b, 0x33, 0xe8, 0x60, 0xaa, 0xcd, 0x3c, 0x0a, 0x79, 0xb1, 0x00, 0xf2,
	0x11, 0x0e, 0x46, 0x36, 0x31, 0x59, 0x8c, 0x6f, 0x05, 0x92, 0x6f, 0x58, 0xc1, 0x0a, 0xab, 0xd4,
	0xcd, 0x35, 0xd1, 0x87, 0x75, 0x93, 0xca, 0x74, 0x89, 0x65, 0x0c, 0x87, 0x95, 0x02, 0xe5, 0x36,
	0x23, 0x36, 0xf2, 0xf6, 0x15, 0xb3, 0x5a, 0x82, 0x81, 0xb8, 0x85, 0xb0, 0x20, 0x74, 0xfc, 0xfb,
	0xfe, 0xf0, 0x42, 0xfd, 0x8a, 0xac, 0xca, 0xbc, 0x31, 0x93, 0xe4, 0x27, 0x1c, 0xc7, 0x98, 0x18,
	0xf2, 0xe8, 0xfe, 0x7d, 0xd8, 0x7a, 0x55, 0xed, 0x6d, 0x55, 0x85, 0xeb, 0x55, 0xc9, 0x3b, 0x38,
	0x69, 0xec, 0xab, 0x54, 0x11, 0xec, 0xa5, 0x48, 0xa4, 0x13, 0xac, 0x2e, 0xa8, 0xe1, 0xf0, 0x2b,
	0x80, 0xf0, 0xa9, 0xf0, 0x33, 0x31, 0x82, 0x0e, 0x37, 0x21, 0xae, 0x36, 0xa4, 0x5b, 0x6d, 0xb9,
	0x3f, 0xf8, 0x9b, 0xb0, 0xb0, 0x93, 0x3b, 0x62, 0x0c, 0xdd, 0xfa, 0x08, 0x21, 0x37, 0xf0, 0x7f,
	0x14, 0xd4, 0xbf, 0xde, 0xca, 0xa9, 0x65, 0x9f, 0x77, 0xf9, 0xc9, 0x3d, 0x7c, 0x07, 0x00, 0x00,
	0xff, 0xff, 0x33, 0xc3, 0xf9, 0x9c, 0x8b, 0x02, 0x00, 0x00,
}
