// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/m3o/api/proto/m3o.proto

package go_micro_api_m3o

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	ProfilePictureUrl    string   `protobuf:"bytes,5,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

type ReadAccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountRequest) Reset()         { *m = ReadAccountRequest{} }
func (m *ReadAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAccountRequest) ProtoMessage()    {}
func (*ReadAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{1}
}

func (m *ReadAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountRequest.Unmarshal(m, b)
}
func (m *ReadAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountRequest.Marshal(b, m, deterministic)
}
func (m *ReadAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountRequest.Merge(m, src)
}
func (m *ReadAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAccountRequest.Size(m)
}
func (m *ReadAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountRequest proto.InternalMessageInfo

type ReadAccountResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAccountResponse) Reset()         { *m = ReadAccountResponse{} }
func (m *ReadAccountResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAccountResponse) ProtoMessage()    {}
func (*ReadAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{2}
}

func (m *ReadAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAccountResponse.Unmarshal(m, b)
}
func (m *ReadAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAccountResponse.Marshal(b, m, deterministic)
}
func (m *ReadAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAccountResponse.Merge(m, src)
}
func (m *ReadAccountResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAccountResponse.Size(m)
}
func (m *ReadAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAccountResponse proto.InternalMessageInfo

func (m *ReadAccountResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type Project struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ApiDomain            string   `protobuf:"bytes,4,opt,name=api_domain,json=apiDomain,proto3" json:"api_domain,omitempty"`
	WebDomain            string   `protobuf:"bytes,5,opt,name=web_domain,json=webDomain,proto3" json:"web_domain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{3}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Project) GetApiDomain() string {
	if m != nil {
		return m.ApiDomain
	}
	return ""
}

func (m *Project) GetWebDomain() string {
	if m != nil {
		return m.WebDomain
	}
	return ""
}

type CreateProjectRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectRequest) Reset()         { *m = CreateProjectRequest{} }
func (m *CreateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*CreateProjectRequest) ProtoMessage()    {}
func (*CreateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{4}
}

func (m *CreateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectRequest.Unmarshal(m, b)
}
func (m *CreateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectRequest.Marshal(b, m, deterministic)
}
func (m *CreateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectRequest.Merge(m, src)
}
func (m *CreateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_CreateProjectRequest.Size(m)
}
func (m *CreateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectRequest proto.InternalMessageInfo

func (m *CreateProjectRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type CreateProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateProjectResponse) Reset()         { *m = CreateProjectResponse{} }
func (m *CreateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*CreateProjectResponse) ProtoMessage()    {}
func (*CreateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{5}
}

func (m *CreateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateProjectResponse.Unmarshal(m, b)
}
func (m *CreateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateProjectResponse.Marshal(b, m, deterministic)
}
func (m *CreateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateProjectResponse.Merge(m, src)
}
func (m *CreateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_CreateProjectResponse.Size(m)
}
func (m *CreateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateProjectResponse proto.InternalMessageInfo

func (m *CreateProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type UpdateProjectRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ApiDomain            string   `protobuf:"bytes,3,opt,name=api_domain,json=apiDomain,proto3" json:"api_domain,omitempty"`
	WebDomain            string   `protobuf:"bytes,4,opt,name=web_domain,json=webDomain,proto3" json:"web_domain,omitempty"`
	Repository           string   `protobuf:"bytes,5,opt,name=repository,proto3" json:"repository,omitempty"`
	GithubToken          string   `protobuf:"bytes,6,opt,name=github_token,json=githubToken,proto3" json:"github_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectRequest) Reset()         { *m = UpdateProjectRequest{} }
func (m *UpdateProjectRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectRequest) ProtoMessage()    {}
func (*UpdateProjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{6}
}

func (m *UpdateProjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectRequest.Unmarshal(m, b)
}
func (m *UpdateProjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectRequest.Merge(m, src)
}
func (m *UpdateProjectRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectRequest.Size(m)
}
func (m *UpdateProjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectRequest proto.InternalMessageInfo

func (m *UpdateProjectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateProjectRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateProjectRequest) GetApiDomain() string {
	if m != nil {
		return m.ApiDomain
	}
	return ""
}

func (m *UpdateProjectRequest) GetWebDomain() string {
	if m != nil {
		return m.WebDomain
	}
	return ""
}

func (m *UpdateProjectRequest) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *UpdateProjectRequest) GetGithubToken() string {
	if m != nil {
		return m.GithubToken
	}
	return ""
}

type UpdateProjectResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProjectResponse) Reset()         { *m = UpdateProjectResponse{} }
func (m *UpdateProjectResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProjectResponse) ProtoMessage()    {}
func (*UpdateProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{7}
}

func (m *UpdateProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProjectResponse.Unmarshal(m, b)
}
func (m *UpdateProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProjectResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProjectResponse.Merge(m, src)
}
func (m *UpdateProjectResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProjectResponse.Size(m)
}
func (m *UpdateProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProjectResponse proto.InternalMessageInfo

type ListProjectsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListProjectsRequest) Reset()         { *m = ListProjectsRequest{} }
func (m *ListProjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListProjectsRequest) ProtoMessage()    {}
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{8}
}

func (m *ListProjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsRequest.Unmarshal(m, b)
}
func (m *ListProjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListProjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsRequest.Merge(m, src)
}
func (m *ListProjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListProjectsRequest.Size(m)
}
func (m *ListProjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsRequest proto.InternalMessageInfo

type ListProjectsResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=Projects,proto3" json:"Projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListProjectsResponse) Reset()         { *m = ListProjectsResponse{} }
func (m *ListProjectsResponse) String() string { return proto.CompactTextString(m) }
func (*ListProjectsResponse) ProtoMessage()    {}
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{9}
}

func (m *ListProjectsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProjectsResponse.Unmarshal(m, b)
}
func (m *ListProjectsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProjectsResponse.Marshal(b, m, deterministic)
}
func (m *ListProjectsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProjectsResponse.Merge(m, src)
}
func (m *ListProjectsResponse) XXX_Size() int {
	return xxx_messageInfo_ListProjectsResponse.Size(m)
}
func (m *ListProjectsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProjectsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListProjectsResponse proto.InternalMessageInfo

func (m *ListProjectsResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

type VerifyGithubTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyGithubTokenRequest) Reset()         { *m = VerifyGithubTokenRequest{} }
func (m *VerifyGithubTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyGithubTokenRequest) ProtoMessage()    {}
func (*VerifyGithubTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{10}
}

func (m *VerifyGithubTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyGithubTokenRequest.Unmarshal(m, b)
}
func (m *VerifyGithubTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyGithubTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyGithubTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyGithubTokenRequest.Merge(m, src)
}
func (m *VerifyGithubTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyGithubTokenRequest.Size(m)
}
func (m *VerifyGithubTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyGithubTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyGithubTokenRequest proto.InternalMessageInfo

func (m *VerifyGithubTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyGithubTokenResponse struct {
	Repos                []string `protobuf:"bytes,1,rep,name=repos,proto3" json:"repos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyGithubTokenResponse) Reset()         { *m = VerifyGithubTokenResponse{} }
func (m *VerifyGithubTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyGithubTokenResponse) ProtoMessage()    {}
func (*VerifyGithubTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_adee7567aa95c263, []int{11}
}

func (m *VerifyGithubTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyGithubTokenResponse.Unmarshal(m, b)
}
func (m *VerifyGithubTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyGithubTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyGithubTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyGithubTokenResponse.Merge(m, src)
}
func (m *VerifyGithubTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyGithubTokenResponse.Size(m)
}
func (m *VerifyGithubTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyGithubTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyGithubTokenResponse proto.InternalMessageInfo

func (m *VerifyGithubTokenResponse) GetRepos() []string {
	if m != nil {
		return m.Repos
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.api.m3o.User")
	proto.RegisterType((*ReadAccountRequest)(nil), "go.micro.api.m3o.ReadAccountRequest")
	proto.RegisterType((*ReadAccountResponse)(nil), "go.micro.api.m3o.ReadAccountResponse")
	proto.RegisterType((*Project)(nil), "go.micro.api.m3o.Project")
	proto.RegisterType((*CreateProjectRequest)(nil), "go.micro.api.m3o.CreateProjectRequest")
	proto.RegisterType((*CreateProjectResponse)(nil), "go.micro.api.m3o.CreateProjectResponse")
	proto.RegisterType((*UpdateProjectRequest)(nil), "go.micro.api.m3o.UpdateProjectRequest")
	proto.RegisterType((*UpdateProjectResponse)(nil), "go.micro.api.m3o.UpdateProjectResponse")
	proto.RegisterType((*ListProjectsRequest)(nil), "go.micro.api.m3o.ListProjectsRequest")
	proto.RegisterType((*ListProjectsResponse)(nil), "go.micro.api.m3o.ListProjectsResponse")
	proto.RegisterType((*VerifyGithubTokenRequest)(nil), "go.micro.api.m3o.VerifyGithubTokenRequest")
	proto.RegisterType((*VerifyGithubTokenResponse)(nil), "go.micro.api.m3o.VerifyGithubTokenResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/m3o/api/proto/m3o.proto", fileDescriptor_adee7567aa95c263)
}

var fileDescriptor_adee7567aa95c263 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x18, 0x5d, 0xda, 0xb4, 0x2c, 0xdf, 0x50, 0xc5, 0xdc, 0x14, 0xb2, 0xf2, 0xa3, 0x11, 0xc1, 0x40,
	0x43, 0x4a, 0x59, 0x2b, 0x1e, 0x60, 0x02, 0x89, 0x0b, 0x06, 0x9a, 0x0a, 0x85, 0x0b, 0x2e, 0x2a,
	0x37, 0x75, 0x8b, 0xa1, 0x89, 0x83, 0xed, 0x30, 0xed, 0x11, 0xb8, 0xe6, 0x86, 0x77, 0xe1, 0xe5,
	0x50, 0xfc, 0xd3, 0xad, 0x4d, 0x58, 0x27, 0xae, 0x1a, 0x9f, 0xef, 0xf8, 0xf3, 0x39, 0xc7, 0x9f,
	0x0b, 0x47, 0x73, 0x2a, 0xbf, 0xe4, 0x93, 0x28, 0x66, 0x49, 0x2f, 0xa1, 0x31, 0x67, 0x3d, 0x41,
	0xf8, 0x0f, 0x1a, 0x13, 0xd1, 0x4b, 0x06, 0xac, 0x87, 0x33, 0xda, 0xcb, 0x38, 0x93, 0xac, 0x58,
	0x45, 0xea, 0x0b, 0xdd, 0x9a, 0xb3, 0x48, 0x51, 0x23, 0x9c, 0xd1, 0x28, 0x19, 0xb0, 0xf0, 0xb7,
	0x03, 0xee, 0x48, 0x10, 0x8e, 0x5a, 0x50, 0xa3, 0xd3, 0xc0, 0xd9, 0x77, 0x9e, 0x7a, 0xc3, 0x1a,
	0x9d, 0xa2, 0xfb, 0x00, 0x33, 0xca, 0x85, 0x1c, 0xa7, 0x38, 0x21, 0x41, 0x4d, 0xe1, 0x9e, 0x42,
	0xde, 0xe1, 0x84, 0xa0, 0xbb, 0xe0, 0x2d, 0xb0, 0xad, 0xd6, 0x55, 0x75, 0xbb, 0x00, 0x54, 0xd1,
	0x87, 0x06, 0x49, 0x30, 0x5d, 0x04, 0xae, 0x2a, 0xe8, 0x05, 0x8a, 0xa0, 0x9d, 0x71, 0x36, 0xa3,
	0x0b, 0x32, 0xce, 0x68, 0x2c, 0x73, 0x4e, 0xc6, 0x39, 0x5f, 0x04, 0x0d, 0xc5, 0xd9, 0x35, 0xa5,
	0x53, 0x5d, 0x19, 0xf1, 0x45, 0xe8, 0x03, 0x1a, 0x12, 0x3c, 0x3d, 0x8e, 0x63, 0x96, 0xa7, 0x72,
	0x48, 0xbe, 0xe7, 0x44, 0xc8, 0xf0, 0x18, 0xda, 0x2b, 0xa8, 0xc8, 0x58, 0x2a, 0x08, 0x3a, 0x04,
	0x37, 0x17, 0x84, 0x2b, 0x03, 0x3b, 0xfd, 0xdb, 0xd1, 0xba, 0xd1, 0xa8, 0x30, 0x39, 0x54, 0x9c,
	0xf0, 0xa7, 0x03, 0x37, 0x4e, 0x39, 0xfb, 0x4a, 0x62, 0x59, 0xb2, 0x8d, 0xc0, 0xbd, 0x64, 0x58,
	0x7d, 0xa3, 0x7b, 0xe0, 0x15, 0xbf, 0x22, 0xc3, 0xb1, 0xf5, 0x7a, 0x01, 0x14, 0x41, 0xe1, 0x8c,
	0x8e, 0xa7, 0x2c, 0xc1, 0x34, 0x35, 0x8e, 0x3d, 0x9c, 0xd1, 0x57, 0x0a, 0x28, 0xca, 0x67, 0x64,
	0x62, 0xcb, 0xda, 0xac, 0x77, 0x46, 0x26, 0xba, 0x1c, 0xbe, 0x01, 0xff, 0x25, 0x27, 0x58, 0x12,
	0x23, 0xc8, 0xd8, 0x44, 0x83, 0xa5, 0x44, 0x63, 0x69, 0xaf, 0x6c, 0xc9, 0x6e, 0xb1, 0xcc, 0xf0,
	0x04, 0x3a, 0x6b, 0xcd, 0x4c, 0x3a, 0xff, 0xd5, 0xed, 0x8f, 0x03, 0xfe, 0x28, 0x9b, 0x96, 0xb5,
	0x5d, 0x27, 0xb3, 0xd5, 0x54, 0xea, 0x57, 0xa7, 0xe2, 0xae, 0xa5, 0x82, 0x1e, 0x00, 0x70, 0x92,
	0x31, 0x41, 0x25, 0xe3, 0xe7, 0x26, 0xb4, 0x4b, 0x08, 0x7a, 0x08, 0x37, 0xf5, 0xf0, 0x8f, 0x25,
	0xfb, 0x46, 0xd2, 0xa0, 0xa9, 0x18, 0x3b, 0x1a, 0xfb, 0x50, 0x40, 0xe1, 0x1d, 0xe8, 0xac, 0x89,
	0xd7, 0x59, 0x84, 0x1d, 0x68, 0x9f, 0x50, 0x21, 0x0d, 0x2c, 0xec, 0x5c, 0xbd, 0x05, 0x7f, 0x15,
	0x36, 0xd1, 0xbd, 0x80, 0x6d, 0x8b, 0x05, 0xce, 0x7e, 0xfd, 0xea, 0xec, 0x96, 0xd4, 0xf0, 0x39,
	0x04, 0x1f, 0x09, 0xa7, 0xb3, 0xf3, 0xd7, 0x17, 0x9a, 0x6c, 0x7e, 0x3e, 0x34, 0xb4, 0x6c, 0x1d,
	0xa1, 0x5e, 0x84, 0x47, 0xb0, 0x57, 0xb1, 0xc3, 0xa8, 0xf0, 0xa1, 0xa1, 0xec, 0x2b, 0x09, 0xde,
	0x50, 0x2f, 0xfa, 0x73, 0x68, 0x99, 0x77, 0xf0, 0x5e, 0xbf, 0x7c, 0x34, 0x02, 0xb7, 0x78, 0x1d,
	0xe8, 0x51, 0x59, 0x63, 0xf9, 0x2d, 0x75, 0x1f, 0x6f, 0x60, 0x99, 0xc4, 0xb6, 0xfa, 0xbf, 0xea,
	0xd0, 0x32, 0xd6, 0xec, 0x49, 0x9f, 0xa1, 0xa9, 0x67, 0x0d, 0x1d, 0x94, 0xbb, 0x54, 0x8d, 0x74,
	0xf7, 0xc9, 0x46, 0x9e, 0x3d, 0xaf, 0x68, 0xae, 0x2f, 0xaf, 0xaa, 0x79, 0xd5, 0x4c, 0x56, 0x35,
	0xaf, 0xbe, 0xfe, 0x2d, 0xf4, 0x09, 0xdc, 0xe2, 0xa6, 0x51, 0x85, 0xfb, 0x8a, 0xc1, 0xe8, 0x1e,
	0x6c, 0xa2, 0x2d, 0x1b, 0xa7, 0xb0, 0x5b, 0xba, 0x41, 0x74, 0x58, 0xde, 0xfe, 0xaf, 0xc1, 0xe8,
	0x3e, 0xbb, 0x16, 0xd7, 0x9e, 0x37, 0x69, 0xaa, 0x3f, 0xf5, 0xc1, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x41, 0xd4, 0x38, 0x09, 0x06, 0x00, 0x00,
}
