// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/charts.proto

package charts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Range                string   `protobuf:"bytes,2,opt,name=range,proto3" json:"range,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_41214dd822a49c8a, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Request) GetRange() string {
	if m != nil {
		return m.Range
	}
	return ""
}

type Chart struct {
	Points               []*Point `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Chart) Reset()         { *m = Chart{} }
func (m *Chart) String() string { return proto.CompactTextString(m) }
func (*Chart) ProtoMessage()    {}
func (*Chart) Descriptor() ([]byte, []int) {
	return fileDescriptor_41214dd822a49c8a, []int{1}
}

func (m *Chart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chart.Unmarshal(m, b)
}
func (m *Chart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chart.Marshal(b, m, deterministic)
}
func (m *Chart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chart.Merge(m, src)
}
func (m *Chart) XXX_Size() int {
	return xxx_messageInfo_Chart.Size(m)
}
func (m *Chart) XXX_DiscardUnknown() {
	xxx_messageInfo_Chart.DiscardUnknown(m)
}

var xxx_messageInfo_Chart proto.InternalMessageInfo

func (m *Chart) GetPoints() []*Point {
	if m != nil {
		return m.Points
	}
	return nil
}

type Point struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Close                float32  `protobuf:"fixed32,2,opt,name=close,proto3" json:"close,omitempty"`
	Volume               float32  `protobuf:"fixed32,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Value                float32  `protobuf:"fixed32,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_41214dd822a49c8a, []int{2}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Point) GetClose() float32 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Point) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Point) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
	proto.RegisterType((*Chart)(nil), "Chart")
	proto.RegisterType((*Point)(nil), "Point")
}

func init() { proto.RegisterFile("proto/charts.proto", fileDescriptor_41214dd822a49c8a) }

var fileDescriptor_41214dd822a49c8a = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x49, 0xdb, 0x98, 0x72, 0x65, 0x3a, 0x21, 0x64, 0x31, 0x54, 0xc5, 0x0b, 0x9d, 0x82,
	0xd4, 0x3e, 0x02, 0x43, 0xc4, 0x56, 0x85, 0x07, 0x40, 0x21, 0x3d, 0x20, 0x22, 0xe4, 0x8a, 0x7d,
	0xce, 0xf3, 0x23, 0x5f, 0xd2, 0xad, 0xdb, 0xff, 0xfd, 0xfe, 0xf5, 0xc9, 0x36, 0xe0, 0xc9, 0xb3,
	0xf0, 0x73, 0xf3, 0x5d, 0x7b, 0x09, 0x85, 0x82, 0xdb, 0xc3, 0x75, 0x45, 0x7f, 0x91, 0x82, 0x20,
	0xc2, 0x22, 0xc6, 0xf6, 0x68, 0xb3, 0x4d, 0xb6, 0xbd, 0xa9, 0x34, 0xe3, 0x1d, 0xe4, 0xbe, 0xee,
	0xbf, 0xc8, 0xce, 0xb4, 0x1c, 0xc1, 0x3d, 0x41, 0xfe, 0x92, 0x24, 0xb8, 0x06, 0x73, 0xe2, 0xb6,
	0x97, 0x60, 0xb3, 0xcd, 0x7c, 0xbb, 0xda, 0x99, 0xe2, 0x90, 0xb0, 0x9a, 0x5a, 0xf7, 0x0e, 0xb9,
	0x16, 0xc9, 0x7d, 0xac, 0x85, 0xce, 0xee, 0x94, 0x93, 0xbb, 0xe9, 0x38, 0x8c, 0xee, 0x59, 0x35,
	0x02, 0xde, 0x83, 0x19, 0xb8, 0x8b, 0xbf, 0x64, 0xe7, 0x5a, 0x4f, 0x94, 0xd6, 0x43, 0xdd, 0x45,
	0xb2, 0x8b, 0x71, 0xad, 0xb0, 0x63, 0x30, 0x7a, 0x93, 0x80, 0x6b, 0x58, 0x96, 0x24, 0x6f, 0xc2,
	0xcd, 0x0f, 0x2e, 0x8b, 0xe9, 0x4d, 0x0f, 0xa6, 0xd0, 0x63, 0x77, 0x85, 0x8f, 0xb0, 0x2a, 0x49,
	0x5e, 0xfb, 0x81, 0x82, 0xb0, 0xbf, 0x38, 0x71, 0x70, 0x5b, 0x92, 0x1c, 0xd8, 0xcb, 0x27, 0x77,
	0x2d, 0x5f, 0xda, 0x7c, 0x18, 0xfd, 0xb6, 0xfd, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0x00,
	0xea, 0x3d, 0x4c, 0x01, 0x00, 0x00,
}
