// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/johnny/johnny.proto

package go_micro_srv_johnny

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Johnny service

type JohnnyService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Johnny_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Johnny_PingPongService, error)
}

type johnnyService struct {
	c    client.Client
	name string
}

func NewJohnnyService(name string, c client.Client) JohnnyService {
	return &johnnyService{
		c:    c,
		name: name,
	}
}

func (c *johnnyService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Johnny.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *johnnyService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Johnny_StreamService, error) {
	req := c.c.NewRequest(c.name, "Johnny.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &johnnyServiceStream{stream}, nil
}

type Johnny_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type johnnyServiceStream struct {
	stream client.Stream
}

func (x *johnnyServiceStream) Close() error {
	return x.stream.Close()
}

func (x *johnnyServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *johnnyServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *johnnyServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *johnnyServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *johnnyService) PingPong(ctx context.Context, opts ...client.CallOption) (Johnny_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Johnny.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &johnnyServicePingPong{stream}, nil
}

type Johnny_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type johnnyServicePingPong struct {
	stream client.Stream
}

func (x *johnnyServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *johnnyServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *johnnyServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *johnnyServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *johnnyServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *johnnyServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Johnny service

type JohnnyHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Johnny_StreamStream) error
	PingPong(context.Context, Johnny_PingPongStream) error
}

func RegisterJohnnyHandler(s server.Server, hdlr JohnnyHandler, opts ...server.HandlerOption) error {
	type johnny interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Johnny struct {
		johnny
	}
	h := &johnnyHandler{hdlr}
	return s.Handle(s.NewHandler(&Johnny{h}, opts...))
}

type johnnyHandler struct {
	JohnnyHandler
}

func (h *johnnyHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.JohnnyHandler.Call(ctx, in, out)
}

func (h *johnnyHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.JohnnyHandler.Stream(ctx, m, &johnnyStreamStream{stream})
}

type Johnny_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type johnnyStreamStream struct {
	stream server.Stream
}

func (x *johnnyStreamStream) Close() error {
	return x.stream.Close()
}

func (x *johnnyStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *johnnyStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *johnnyStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *johnnyStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *johnnyHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.JohnnyHandler.PingPong(ctx, &johnnyPingPongStream{stream})
}

type Johnny_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type johnnyPingPongStream struct {
	stream server.Stream
}

func (x *johnnyPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *johnnyPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *johnnyPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *johnnyPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *johnnyPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *johnnyPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
