// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/home/home.proto

package go_micro_api_home

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category             string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Icon                 string   `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *App) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{2}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{3}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ListAppsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsRequest) Reset()         { *m = ListAppsRequest{} }
func (m *ListAppsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAppsRequest) ProtoMessage()    {}
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{4}
}

func (m *ListAppsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsRequest.Unmarshal(m, b)
}
func (m *ListAppsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsRequest.Marshal(b, m, deterministic)
}
func (m *ListAppsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsRequest.Merge(m, src)
}
func (m *ListAppsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAppsRequest.Size(m)
}
func (m *ListAppsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsRequest proto.InternalMessageInfo

type ListAppsResponse struct {
	Apps                 []*App   `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAppsResponse) Reset()         { *m = ListAppsResponse{} }
func (m *ListAppsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAppsResponse) ProtoMessage()    {}
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33e371a295d94392, []int{5}
}

func (m *ListAppsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAppsResponse.Unmarshal(m, b)
}
func (m *ListAppsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAppsResponse.Marshal(b, m, deterministic)
}
func (m *ListAppsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAppsResponse.Merge(m, src)
}
func (m *ListAppsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAppsResponse.Size(m)
}
func (m *ListAppsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAppsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAppsResponse proto.InternalMessageInfo

func (m *ListAppsResponse) GetApps() []*App {
	if m != nil {
		return m.Apps
	}
	return nil
}

func init() {
	proto.RegisterType((*App)(nil), "go.micro.api.home.App")
	proto.RegisterType((*User)(nil), "go.micro.api.home.User")
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.home.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.home.ReadUserResponse")
	proto.RegisterType((*ListAppsRequest)(nil), "go.micro.api.home.ListAppsRequest")
	proto.RegisterType((*ListAppsResponse)(nil), "go.micro.api.home.ListAppsResponse")
}

func init() { proto.RegisterFile("proto/home/home.proto", fileDescriptor_33e371a295d94392) }

var fileDescriptor_33e371a295d94392 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xb3, 0xfc, 0x49, 0xa6, 0xf0, 0xb7, 0x5d, 0x50, 0x43, 0x45, 0x28, 0xf1, 0x52,
	0x14, 0x56, 0x88, 0x77, 0x25, 0x9e, 0x3c, 0x88, 0x87, 0x14, 0x0f, 0x9e, 0x64, 0x4d, 0xd6, 0xba,
	0x60, 0xb2, 0xe3, 0x6e, 0x7a, 0xf0, 0x5b, 0xf9, 0x11, 0x65, 0x27, 0x8d, 0x85, 0x18, 0xbc, 0x84,
	0x99, 0x37, 0x2f, 0xbf, 0x99, 0x07, 0x0b, 0x87, 0x68, 0x4d, 0x6b, 0x2e, 0xdf, 0x4c, 0xad, 0xe8,
	0x23, 0xa8, 0xe7, 0xf3, 0x8d, 0x11, 0xb5, 0x2e, 0xad, 0x11, 0x12, 0xb5, 0xf0, 0x83, 0xf4, 0x09,
	0xc2, 0x1c, 0x91, 0xff, 0x87, 0x89, 0xae, 0x92, 0x60, 0x19, 0xac, 0xe2, 0x62, 0xa2, 0x2b, 0xce,
	0x81, 0x35, 0xb2, 0x56, 0xc9, 0x84, 0x14, 0xaa, 0xf9, 0x02, 0xa2, 0x52, 0xb6, 0x6a, 0x63, 0xec,
	0x67, 0x12, 0x92, 0xfe, 0xd3, 0x7b, 0xbf, 0x2e, 0x4d, 0x93, 0xb0, 0xce, 0xef, 0xeb, 0xf4, 0x16,
	0xd8, 0xa3, 0x53, 0x96, 0x9f, 0x02, 0xbc, 0x6a, 0xeb, 0xda, 0x67, 0x22, 0x76, 0x3b, 0x62, 0x52,
	0x1e, 0x3c, 0xf6, 0x04, 0xe2, 0x77, 0xd9, 0x4f, 0xbb, 0x7d, 0x91, 0x17, 0xfc, 0x30, 0x9d, 0xc3,
	0x41, 0xa1, 0x64, 0xe5, 0x39, 0x85, 0xfa, 0xd8, 0x2a, 0xd7, 0xa6, 0x37, 0x30, 0xdb, 0x4b, 0x0e,
	0x4d, 0xe3, 0x14, 0xbf, 0x00, 0xb6, 0x75, 0xca, 0x12, 0x7c, 0x9a, 0x1d, 0x8b, 0x5f, 0x39, 0x05,
	0xd9, 0xc9, 0xe4, 0x99, 0xf7, 0xda, 0xb5, 0x39, 0xa2, 0xeb, 0x99, 0xd7, 0x30, 0xdb, 0x4b, 0x3b,
	0xe6, 0x39, 0x30, 0x89, 0xe8, 0x92, 0x60, 0x19, 0xae, 0xa6, 0xd9, 0xd1, 0x08, 0x33, 0x47, 0x2c,
	0xc8, 0x93, 0x7d, 0x05, 0xc0, 0xee, 0x4c, 0xad, 0xf8, 0x1a, 0xa2, 0xfe, 0x38, 0x9e, 0x8e, 0xfc,
	0x32, 0x08, 0xb3, 0x38, 0xfb, 0xd3, 0xb3, 0xbb, 0x64, 0x0d, 0x51, 0x7f, 0xdd, 0x28, 0x74, 0x90,
	0x66, 0x14, 0x3a, 0x8c, 0xf7, 0xf2, 0x8f, 0x9e, 0xc4, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x6e, 0x56, 0x71, 0x2b, 0x02, 0x00, 0x00,
}
