// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/notifications/notifications.proto

package go_micro_service_notifications

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SubscribeRequest struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{0}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *SubscribeRequest) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type SubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{1}
}

func (m *SubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeResponse.Unmarshal(m, b)
}
func (m *SubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeResponse.Marshal(b, m, deterministic)
}
func (m *SubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeResponse.Merge(m, src)
}
func (m *SubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_SubscribeResponse.Size(m)
}
func (m *SubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeResponse proto.InternalMessageInfo

type UnsubscribeRequest struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{2}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *UnsubscribeRequest) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type UnsubscribeResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeResponse) Reset()         { *m = UnsubscribeResponse{} }
func (m *UnsubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeResponse) ProtoMessage()    {}
func (*UnsubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{3}
}

func (m *UnsubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeResponse.Unmarshal(m, b)
}
func (m *UnsubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeResponse.Marshal(b, m, deterministic)
}
func (m *UnsubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeResponse.Merge(m, src)
}
func (m *UnsubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeResponse.Size(m)
}
func (m *UnsubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeResponse proto.InternalMessageInfo

type MarkAsReadRequest struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkAsReadRequest) Reset()         { *m = MarkAsReadRequest{} }
func (m *MarkAsReadRequest) String() string { return proto.CompactTextString(m) }
func (*MarkAsReadRequest) ProtoMessage()    {}
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{4}
}

func (m *MarkAsReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkAsReadRequest.Unmarshal(m, b)
}
func (m *MarkAsReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkAsReadRequest.Marshal(b, m, deterministic)
}
func (m *MarkAsReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkAsReadRequest.Merge(m, src)
}
func (m *MarkAsReadRequest) XXX_Size() int {
	return xxx_messageInfo_MarkAsReadRequest.Size(m)
}
func (m *MarkAsReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkAsReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarkAsReadRequest proto.InternalMessageInfo

func (m *MarkAsReadRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type MarkAsReadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarkAsReadResponse) Reset()         { *m = MarkAsReadResponse{} }
func (m *MarkAsReadResponse) String() string { return proto.CompactTextString(m) }
func (*MarkAsReadResponse) ProtoMessage()    {}
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{5}
}

func (m *MarkAsReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarkAsReadResponse.Unmarshal(m, b)
}
func (m *MarkAsReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarkAsReadResponse.Marshal(b, m, deterministic)
}
func (m *MarkAsReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarkAsReadResponse.Merge(m, src)
}
func (m *MarkAsReadResponse) XXX_Size() int {
	return xxx_messageInfo_MarkAsReadResponse.Size(m)
}
func (m *MarkAsReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarkAsReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarkAsReadResponse proto.InternalMessageInfo

type NotifyRequest struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyRequest) Reset()         { *m = NotifyRequest{} }
func (m *NotifyRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyRequest) ProtoMessage()    {}
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{6}
}

func (m *NotifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyRequest.Unmarshal(m, b)
}
func (m *NotifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyRequest.Marshal(b, m, deterministic)
}
func (m *NotifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyRequest.Merge(m, src)
}
func (m *NotifyRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyRequest.Size(m)
}
func (m *NotifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyRequest proto.InternalMessageInfo

func (m *NotifyRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *NotifyRequest) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *NotifyRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type NotifyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyResponse) Reset()         { *m = NotifyResponse{} }
func (m *NotifyResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyResponse) ProtoMessage()    {}
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{7}
}

func (m *NotifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyResponse.Unmarshal(m, b)
}
func (m *NotifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyResponse.Marshal(b, m, deterministic)
}
func (m *NotifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyResponse.Merge(m, src)
}
func (m *NotifyResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyResponse.Size(m)
}
func (m *NotifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyResponse proto.InternalMessageInfo

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{8}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Notifications        []*Notification `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{9}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetNotifications() []*Notification {
	if m != nil {
		return m.Notifications
	}
	return nil
}

type Notification struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ResourceId           string   `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ReadTimestamp        int64    `protobuf:"varint,6,opt,name=read_timestamp,json=readTimestamp,proto3" json:"read_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{10}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Notification) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Notification) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *Notification) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Notification) GetReadTimestamp() int64 {
	if m != nil {
		return m.ReadTimestamp
	}
	return 0
}

type ListSubscribptionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSubscribptionsRequest) Reset()         { *m = ListSubscribptionsRequest{} }
func (m *ListSubscribptionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListSubscribptionsRequest) ProtoMessage()    {}
func (*ListSubscribptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{11}
}

func (m *ListSubscribptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscribptionsRequest.Unmarshal(m, b)
}
func (m *ListSubscribptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscribptionsRequest.Marshal(b, m, deterministic)
}
func (m *ListSubscribptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscribptionsRequest.Merge(m, src)
}
func (m *ListSubscribptionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListSubscribptionsRequest.Size(m)
}
func (m *ListSubscribptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscribptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscribptionsRequest proto.InternalMessageInfo

type ListSubscriptionsResponse struct {
	Subscriptions        []*Subscription `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSubscriptionsResponse) Reset()         { *m = ListSubscriptionsResponse{} }
func (m *ListSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListSubscriptionsResponse) ProtoMessage()    {}
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{12}
}

func (m *ListSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSubscriptionsResponse.Unmarshal(m, b)
}
func (m *ListSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *ListSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSubscriptionsResponse.Merge(m, src)
}
func (m *ListSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListSubscriptionsResponse.Size(m)
}
func (m *ListSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSubscriptionsResponse proto.InternalMessageInfo

func (m *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

type Subscription struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceId           string   `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ResourceType         string   `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{13}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *Subscription) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

type Event struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea36a5f54e9c0f0b, []int{14}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "go.micro.service.notifications.SubscribeRequest")
	proto.RegisterType((*SubscribeResponse)(nil), "go.micro.service.notifications.SubscribeResponse")
	proto.RegisterType((*UnsubscribeRequest)(nil), "go.micro.service.notifications.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeResponse)(nil), "go.micro.service.notifications.UnsubscribeResponse")
	proto.RegisterType((*MarkAsReadRequest)(nil), "go.micro.service.notifications.MarkAsReadRequest")
	proto.RegisterType((*MarkAsReadResponse)(nil), "go.micro.service.notifications.MarkAsReadResponse")
	proto.RegisterType((*NotifyRequest)(nil), "go.micro.service.notifications.NotifyRequest")
	proto.RegisterType((*NotifyResponse)(nil), "go.micro.service.notifications.NotifyResponse")
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.notifications.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "go.micro.service.notifications.ListResponse")
	proto.RegisterType((*Notification)(nil), "go.micro.service.notifications.Notification")
	proto.RegisterType((*ListSubscribptionsRequest)(nil), "go.micro.service.notifications.ListSubscribptionsRequest")
	proto.RegisterType((*ListSubscriptionsResponse)(nil), "go.micro.service.notifications.ListSubscriptionsResponse")
	proto.RegisterType((*Subscription)(nil), "go.micro.service.notifications.Subscription")
	proto.RegisterType((*Event)(nil), "go.micro.service.notifications.Event")
}

func init() {
	proto.RegisterFile("proto/notifications/notifications.proto", fileDescriptor_ea36a5f54e9c0f0b)
}

var fileDescriptor_ea36a5f54e9c0f0b = []byte{
	// 536 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xde, 0x24, 0x6d, 0xa5, 0xa7, 0x49, 0x69, 0xcf, 0x2a, 0xc4, 0x28, 0x5a, 0x46, 0x16, 0x0b,
	0xae, 0x51, 0xbb, 0x78, 0xe1, 0xa5, 0x17, 0x5e, 0x08, 0xba, 0x17, 0x71, 0x05, 0xf1, 0x66, 0x49,
	0x93, 0x71, 0x19, 0xb4, 0x99, 0x98, 0x49, 0x17, 0xfb, 0x0c, 0x3e, 0x96, 0x6f, 0xe0, 0x13, 0x49,
	0x7e, 0x26, 0x9d, 0xd9, 0x16, 0x93, 0x82, 0xde, 0xe5, 0x9c, 0xf3, 0x9d, 0xbf, 0x6f, 0xe6, 0x9b,
	0xc0, 0xe3, 0x34, 0xe3, 0x39, 0x7f, 0x96, 0xf0, 0x9c, 0x7d, 0x61, 0x51, 0x98, 0x33, 0x9e, 0x08,
	0xdd, 0xf2, 0x4b, 0x04, 0x3e, 0xb8, 0xe2, 0xfe, 0x8a, 0x45, 0x19, 0xf7, 0x05, 0xcd, 0xae, 0x59,
	0x44, 0x7d, 0x0d, 0x45, 0x3e, 0xc1, 0xe4, 0xc3, 0x7a, 0x29, 0xa2, 0x8c, 0x2d, 0x69, 0x40, 0xbf,
	0xaf, 0xa9, 0xc8, 0xf1, 0x21, 0x8c, 0x32, 0x2a, 0xf8, 0x3a, 0x8b, 0xe8, 0x25, 0x8b, 0x5d, 0x63,
	0x66, 0xcc, 0x87, 0x01, 0x48, 0xd7, 0xdb, 0x18, 0x1f, 0x81, 0xd3, 0x00, 0xf2, 0x4d, 0x4a, 0x5d,
	0xb3, 0x84, 0xd8, 0xd2, 0x79, 0xb1, 0x49, 0x29, 0x39, 0x86, 0xa9, 0x52, 0x59, 0xa4, 0x3c, 0x11,
	0x94, 0x7c, 0x06, 0xfc, 0x98, 0x88, 0xff, 0xd3, 0xf0, 0x0e, 0x1c, 0x6b, 0xb5, 0xeb, 0x96, 0x27,
	0x30, 0x7d, 0x1f, 0x66, 0x5f, 0x5f, 0x8b, 0x80, 0x86, 0xb1, 0xec, 0x38, 0x01, 0x8b, 0xc5, 0xc2,
	0x35, 0x66, 0xd6, 0x7c, 0x18, 0x14, 0x9f, 0xe4, 0x36, 0xa0, 0x0a, 0xab, 0x93, 0x39, 0x38, 0xe7,
	0x05, 0x5f, 0x9b, 0x7f, 0x3a, 0x2a, 0xba, 0x70, 0x6b, 0x45, 0x85, 0x08, 0xaf, 0xa8, 0x6b, 0x95,
	0x61, 0x69, 0x92, 0x09, 0x8c, 0x65, 0xc3, 0x7a, 0x04, 0x07, 0x46, 0xef, 0x98, 0xc8, 0xeb, 0x01,
	0xc8, 0x12, 0xec, 0xca, 0xac, 0xc2, 0x18, 0x80, 0xa3, 0x9d, 0x68, 0xb9, 0xd3, 0x68, 0x71, 0xea,
	0xff, 0xfd, 0xe0, 0xfd, 0x73, 0xc5, 0x0a, 0xf4, 0x12, 0xe4, 0x97, 0x01, 0xb6, 0x1a, 0xc7, 0x31,
	0x98, 0xcd, 0xb2, 0x26, 0x8b, 0xd5, 0xf9, 0x4d, 0x6d, 0xfe, 0x9b, 0xfc, 0x58, 0xed, 0xfc, 0xf4,
	0xf6, 0xf0, 0x73, 0x1f, 0x86, 0x39, 0x5b, 0x51, 0x91, 0x87, 0xab, 0xd4, 0xed, 0xcf, 0x8c, 0xb9,
	0x15, 0x6c, 0x1d, 0x78, 0x02, 0xe3, 0x8c, 0x86, 0xf1, 0xe5, 0x16, 0x32, 0x28, 0x21, 0x4e, 0xe1,
	0xbd, 0x90, 0x4e, 0x72, 0x0f, 0xee, 0x16, 0x4c, 0xc9, 0x4b, 0x98, 0x96, 0xbb, 0x49, 0x1a, 0xb9,
	0x16, 0x94, 0xb1, 0x2d, 0xa7, 0x42, 0x0d, 0x74, 0xe5, 0x54, 0xad, 0x16, 0xe8, 0x25, 0x48, 0x0c,
	0xb6, 0x1a, 0xde, 0xa1, 0xf4, 0x06, 0x71, 0x66, 0x3b, 0x71, 0xd6, 0x1e, 0x0d, 0xbc, 0x84, 0xfe,
	0x9b, 0x6b, 0x9a, 0xe4, 0x88, 0xd0, 0x2b, 0x41, 0x55, 0x83, 0xf2, 0xbb, 0x38, 0xb5, 0x34, 0xdc,
	0x7c, 0xe3, 0x61, 0x55, 0xde, 0x0e, 0xa4, 0xb9, 0xf8, 0xdd, 0xaf, 0xef, 0xb9, 0x5c, 0x05, 0x33,
	0x18, 0x36, 0xea, 0xc5, 0xe7, 0x1d, 0x17, 0x6f, 0x14, 0xed, 0xbd, 0x38, 0x20, 0xa3, 0xbe, 0xe7,
	0x47, 0xf8, 0x03, 0x46, 0x8a, 0x80, 0x71, 0xd1, 0x56, 0x63, 0xf7, 0x25, 0xf1, 0xce, 0x0e, 0xca,
	0x69, 0x3a, 0xaf, 0x01, 0xb6, 0xe2, 0xc7, 0xd6, 0xe1, 0x77, 0xde, 0x13, 0x6f, 0x71, 0x48, 0x4a,
	0xd3, 0x96, 0xc1, 0xa0, 0x12, 0x3b, 0x3e, 0xed, 0x24, 0x57, 0xf9, 0x0a, 0x79, 0x7e, 0x57, 0x78,
	0xd3, 0x2a, 0x82, 0x5e, 0x71, 0xdf, 0xf1, 0x49, 0x5b, 0xa6, 0xf2, 0xd6, 0x78, 0xa7, 0xdd, 0xc0,
	0x4d, 0x93, 0x9f, 0x06, 0x4c, 0x77, 0x54, 0x85, 0xaf, 0xba, 0x54, 0xd9, 0xab, 0x52, 0xef, 0x90,
	0x54, 0x5d, 0xc3, 0xe4, 0x68, 0x39, 0x28, 0xff, 0x80, 0x67, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xc4, 0xee, 0xb3, 0xb9, 0x2c, 0x07, 0x00, 0x00,
}
