// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/posts.proto

package posts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Feed struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Uuid                 string   `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feed) Reset()         { *m = Feed{} }
func (m *Feed) String() string { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()    {}
func (*Feed) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{0}
}

func (m *Feed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feed.Unmarshal(m, b)
}
func (m *Feed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feed.Marshal(b, m, deterministic)
}
func (m *Feed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feed.Merge(m, src)
}
func (m *Feed) XXX_Size() int {
	return xxx_messageInfo_Feed.Size(m)
}
func (m *Feed) XXX_DiscardUnknown() {
	xxx_messageInfo_Feed.DiscardUnknown(m)
}

var xxx_messageInfo_Feed proto.InternalMessageInfo

func (m *Feed) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Feed) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type CountByUserRequest struct {
	UserUuids            []string `protobuf:"bytes,1,rep,name=user_uuids,json=userUuids,proto3" json:"user_uuids,omitempty"`
	StartTime            int64    `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              int64    `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountByUserRequest) Reset()         { *m = CountByUserRequest{} }
func (m *CountByUserRequest) String() string { return proto.CompactTextString(m) }
func (*CountByUserRequest) ProtoMessage()    {}
func (*CountByUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{1}
}

func (m *CountByUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountByUserRequest.Unmarshal(m, b)
}
func (m *CountByUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountByUserRequest.Marshal(b, m, deterministic)
}
func (m *CountByUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountByUserRequest.Merge(m, src)
}
func (m *CountByUserRequest) XXX_Size() int {
	return xxx_messageInfo_CountByUserRequest.Size(m)
}
func (m *CountByUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountByUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountByUserRequest proto.InternalMessageInfo

func (m *CountByUserRequest) GetUserUuids() []string {
	if m != nil {
		return m.UserUuids
	}
	return nil
}

func (m *CountByUserRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CountByUserRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type CountByUserResponse struct {
	Counts               []*CountResponse `protobuf:"bytes,1,rep,name=counts,proto3" json:"counts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CountByUserResponse) Reset()         { *m = CountByUserResponse{} }
func (m *CountByUserResponse) String() string { return proto.CompactTextString(m) }
func (*CountByUserResponse) ProtoMessage()    {}
func (*CountByUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{2}
}

func (m *CountByUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountByUserResponse.Unmarshal(m, b)
}
func (m *CountByUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountByUserResponse.Marshal(b, m, deterministic)
}
func (m *CountByUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountByUserResponse.Merge(m, src)
}
func (m *CountByUserResponse) XXX_Size() int {
	return xxx_messageInfo_CountByUserResponse.Size(m)
}
func (m *CountByUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountByUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountByUserResponse proto.InternalMessageInfo

func (m *CountByUserResponse) GetCounts() []*CountResponse {
	if m != nil {
		return m.Counts
	}
	return nil
}

type Post struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	FeedType             string   `protobuf:"bytes,3,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`
	FeedUuid             string   `protobuf:"bytes,4,opt,name=feed_uuid,json=feedUuid,proto3" json:"feed_uuid,omitempty"`
	Text                 string   `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Title                string   `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	AttachmentPictureId  string   `protobuf:"bytes,8,opt,name=attachment_picture_id,json=attachmentPictureId,proto3" json:"attachment_picture_id,omitempty"`
	AttachmentLinkUrl    string   `protobuf:"bytes,9,opt,name=attachment_link_url,json=attachmentLinkUrl,proto3" json:"attachment_link_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{3}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Post) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *Post) GetFeedType() string {
	if m != nil {
		return m.FeedType
	}
	return ""
}

func (m *Post) GetFeedUuid() string {
	if m != nil {
		return m.FeedUuid
	}
	return ""
}

func (m *Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Post) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetAttachmentPictureId() string {
	if m != nil {
		return m.AttachmentPictureId
	}
	return ""
}

func (m *Post) GetAttachmentLinkUrl() string {
	if m != nil {
		return m.AttachmentLinkUrl
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Post                 *Post    `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type ListRequest struct {
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int32    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	UserUuid             string   `protobuf:"bytes,4,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{6}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *ListRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListRequest) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type ListResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Posts                []*Post  `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{7}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ListResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type CountResponse struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e93dc7d934d9dc10, []int{8}
}

func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (m *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(m, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CountResponse) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func init() {
	proto.RegisterType((*Feed)(nil), "Feed")
	proto.RegisterType((*CountByUserRequest)(nil), "CountByUserRequest")
	proto.RegisterType((*CountByUserResponse)(nil), "CountByUserResponse")
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
	proto.RegisterType((*CountResponse)(nil), "CountResponse")
}

func init() { proto.RegisterFile("proto/posts.proto", fileDescriptor_e93dc7d934d9dc10) }

var fileDescriptor_e93dc7d934d9dc10 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x6d, 0x12, 0xaf, 0x1b, 0x4f, 0x5a, 0xa4, 0x6e, 0x8b, 0xe4, 0x7e, 0x20, 0x55, 0x2b, 0x01,
	0xe5, 0xb2, 0x48, 0x41, 0x5c, 0x90, 0x38, 0xd0, 0xf2, 0xa1, 0x4a, 0x3d, 0x54, 0x56, 0x73, 0xb6,
	0x82, 0x3d, 0x80, 0xa9, 0xbf, 0xf0, 0xae, 0xa5, 0xf6, 0xcf, 0xf0, 0x3f, 0xb9, 0xa1, 0x99, 0xb5,
	0x9b, 0x84, 0x06, 0xca, 0xc9, 0xbb, 0xef, 0xed, 0xcc, 0x3c, 0xbf, 0x99, 0x5d, 0xd8, 0xa9, 0x9b,
	0xca, 0x56, 0x2f, 0xeb, 0xca, 0x58, 0xa3, 0x79, 0xad, 0x34, 0x78, 0x1f, 0x11, 0x53, 0x29, 0xc1,
	0xb3, 0xb7, 0x35, 0x86, 0x83, 0xe3, 0xc1, 0x49, 0x10, 0xf1, 0x9a, 0xb0, 0xb6, 0xcd, 0xd2, 0x70,
	0xe8, 0x30, 0x5a, 0xab, 0x02, 0xe4, 0x59, 0xd5, 0x96, 0xf6, 0xf4, 0x76, 0x66, 0xb0, 0x89, 0xf0,
	0x47, 0x8b, 0xc6, 0xca, 0x27, 0x00, 0xad, 0xc1, 0x26, 0xa6, 0x23, 0x26, 0x1c, 0x1c, 0x8f, 0x4e,
	0x82, 0x28, 0x20, 0x64, 0x46, 0x00, 0xd1, 0xc6, 0xce, 0x1b, 0x1b, 0xdb, 0xac, 0x40, 0x4e, 0x37,
	0x8a, 0x02, 0x46, 0xae, 0xb2, 0x02, 0xe5, 0x3e, 0x8c, 0xb1, 0x4c, 0x1d, 0x39, 0x62, 0x72, 0x13,
	0xcb, 0x94, 0x28, 0xf5, 0x16, 0x76, 0x57, 0xca, 0x99, 0xba, 0x2a, 0x0d, 0xca, 0x67, 0xe0, 0x27,
	0x04, 0xbb, 0x5a, 0x93, 0xe9, 0x23, 0xcd, 0xa7, 0x7a, 0x3e, 0xea, 0x58, 0xf5, 0x73, 0x08, 0xde,
	0x65, 0x65, 0xec, 0xdd, 0xaf, 0x0c, 0x16, 0xbf, 0x22, 0x0f, 0x21, 0xb8, 0x13, 0xdd, 0xfd, 0xe3,
	0xb8, 0xd7, 0x4c, 0xe4, 0x17, 0xc4, 0x34, 0x66, 0x53, 0x46, 0x8e, 0x24, 0xe0, 0x8a, 0x8c, 0xe9,
	0x49, 0x8e, 0xf4, 0x16, 0x24, 0x47, 0x92, 0x93, 0x78, 0x63, 0x43, 0xd1, 0x39, 0x89, 0x37, 0xec,
	0x4f, 0xd2, 0xe0, 0xdc, 0x62, 0x1a, 0xcf, 0x6d, 0xe8, 0x3b, 0x03, 0x3a, 0xe4, 0x9d, 0x95, 0x7b,
	0x20, 0x6c, 0x66, 0x73, 0x0c, 0x37, 0x39, 0xc6, 0x6d, 0xe4, 0x14, 0x1e, 0xcf, 0xad, 0x9d, 0x27,
	0xdf, 0x0a, 0x2c, 0x6d, 0x5c, 0x67, 0x89, 0x6d, 0x1b, 0x8c, 0xb3, 0x34, 0x1c, 0xf3, 0xa9, 0xdd,
	0x05, 0x79, 0xe9, 0xb8, 0xf3, 0x54, 0x6a, 0x58, 0x82, 0xe3, 0x3c, 0x2b, 0xaf, 0xe3, 0xb6, 0xc9,
	0xc3, 0x80, 0x23, 0x76, 0x16, 0xd4, 0x45, 0x56, 0x5e, 0xcf, 0x9a, 0x5c, 0xbd, 0x06, 0xf1, 0xa1,
	0x69, 0xaa, 0x86, 0x54, 0x27, 0x55, 0xea, 0xfa, 0x2f, 0x22, 0x5e, 0xcb, 0x10, 0x36, 0x0b, 0x34,
	0x66, 0xfe, 0x15, 0x3b, 0x7b, 0xfa, 0xad, 0x3a, 0x83, 0xf1, 0x5d, 0x2f, 0x8e, 0x40, 0x20, 0xa5,
	0xe0, 0xd0, 0xc9, 0xd4, 0xd7, 0x9c, 0x30, 0x72, 0xa0, 0xdc, 0x07, 0x8f, 0xc6, 0x8d, 0x13, 0x4c,
	0xa6, 0x42, 0x53, 0x37, 0x22, 0x86, 0xd4, 0x77, 0x98, 0x5c, 0x64, 0xc6, 0xf6, 0x33, 0xb4, 0x07,
	0x62, 0x79, 0x7c, 0xdc, 0x86, 0xd0, 0x3c, 0x2b, 0x32, 0x97, 0x40, 0x44, 0x6e, 0x43, 0x6a, 0x6b,
	0x92, 0x35, 0x72, 0x6a, 0x69, 0xbd, 0xda, 0x4e, 0x6f, 0xb5, 0x9d, 0xea, 0x1c, 0xb6, 0x5c, 0xad,
	0xff, 0x12, 0x7d, 0x08, 0x82, 0xef, 0x48, 0x38, 0xe4, 0xe9, 0xea, 0x54, 0x3b, 0x4c, 0x9d, 0xc2,
	0xf6, 0xca, 0xb0, 0x91, 0x44, 0x1e, 0xb7, 0xce, 0x3b, 0xb7, 0xf9, 0xe7, 0x74, 0x4d, 0x7f, 0x0d,
	0x41, 0x50, 0x4e, 0x23, 0x8f, 0xc0, 0x3f, 0xe3, 0x39, 0x90, 0xae, 0xca, 0x41, 0xa0, 0xfb, 0xc4,
	0x6a, 0x43, 0xee, 0xc3, 0xe8, 0x13, 0xda, 0xb5, 0xd4, 0x11, 0xf8, 0xb3, 0x3a, 0xfd, 0x5b, 0xe0,
	0x53, 0xf0, 0xe8, 0x7f, 0xe5, 0x96, 0x5e, 0xb2, 0xf8, 0x60, 0x5b, 0x2f, 0x9b, 0xa0, 0x36, 0xa4,
	0x82, 0x31, 0x21, 0xfc, 0x02, 0x08, 0x4d, 0x9f, 0xfb, 0x67, 0x5e, 0xb8, 0x33, 0x74, 0xff, 0x1e,
	0x4a, 0xf7, 0x1c, 0xfc, 0x08, 0x13, 0x2c, 0x1f, 0xac, 0x7b, 0x0c, 0x82, 0x3d, 0xec, 0xb5, 0xff,
	0x71, 0x7f, 0xd5, 0x86, 0x7c, 0x03, 0x93, 0xa5, 0x8b, 0x2f, 0x77, 0xf5, 0xfd, 0x57, 0xe7, 0x60,
	0x4f, 0xaf, 0x79, 0x1b, 0x9c, 0x35, 0xef, 0x31, 0xc7, 0xf5, 0xd6, 0x7c, 0xf6, 0xf9, 0xe1, 0x7b,
	0xf5, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x88, 0xaa, 0x76, 0x0d, 0x05, 0x00, 0x00,
}
