// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cruftbarron/cruftbarron.proto

package go_micro_srv_cruftbarron

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Cruftbarron service

type CruftbarronService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cruftbarron_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Cruftbarron_PingPongService, error)
}

type cruftbarronService struct {
	c    client.Client
	name string
}

func NewCruftbarronService(name string, c client.Client) CruftbarronService {
	return &cruftbarronService{
		c:    c,
		name: name,
	}
}

func (c *cruftbarronService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Cruftbarron.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cruftbarronService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Cruftbarron_StreamService, error) {
	req := c.c.NewRequest(c.name, "Cruftbarron.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &cruftbarronServiceStream{stream}, nil
}

type Cruftbarron_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type cruftbarronServiceStream struct {
	stream client.Stream
}

func (x *cruftbarronServiceStream) Close() error {
	return x.stream.Close()
}

func (x *cruftbarronServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cruftbarronServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cruftbarronServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cruftbarronServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cruftbarronService) PingPong(ctx context.Context, opts ...client.CallOption) (Cruftbarron_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Cruftbarron.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &cruftbarronServicePingPong{stream}, nil
}

type Cruftbarron_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type cruftbarronServicePingPong struct {
	stream client.Stream
}

func (x *cruftbarronServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *cruftbarronServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *cruftbarronServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cruftbarronServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cruftbarronServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *cruftbarronServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Cruftbarron service

type CruftbarronHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Cruftbarron_StreamStream) error
	PingPong(context.Context, Cruftbarron_PingPongStream) error
}

func RegisterCruftbarronHandler(s server.Server, hdlr CruftbarronHandler, opts ...server.HandlerOption) error {
	type cruftbarron interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Cruftbarron struct {
		cruftbarron
	}
	h := &cruftbarronHandler{hdlr}
	return s.Handle(s.NewHandler(&Cruftbarron{h}, opts...))
}

type cruftbarronHandler struct {
	CruftbarronHandler
}

func (h *cruftbarronHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.CruftbarronHandler.Call(ctx, in, out)
}

func (h *cruftbarronHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CruftbarronHandler.Stream(ctx, m, &cruftbarronStreamStream{stream})
}

type Cruftbarron_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type cruftbarronStreamStream struct {
	stream server.Stream
}

func (x *cruftbarronStreamStream) Close() error {
	return x.stream.Close()
}

func (x *cruftbarronStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cruftbarronStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cruftbarronStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cruftbarronStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *cruftbarronHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CruftbarronHandler.PingPong(ctx, &cruftbarronPingPongStream{stream})
}

type Cruftbarron_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type cruftbarronPingPongStream struct {
	stream server.Stream
}

func (x *cruftbarronPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *cruftbarronPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *cruftbarronPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *cruftbarronPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *cruftbarronPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *cruftbarronPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
