// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: github.com/micro/services/pong/proto/pong.proto

package pong

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Pong service

type PongService interface {
	Pong(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type pongService struct {
	c    client.Client
	name string
}

func NewPongService(name string, c client.Client) PongService {
	return &pongService{
		c:    c,
		name: name,
	}
}

func (c *pongService) Pong(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Pong.Pong", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pong service

type PongHandler interface {
	Pong(context.Context, *Request, *Response) error
}

func RegisterPongHandler(s server.Server, hdlr PongHandler, opts ...server.HandlerOption) error {
	type pong interface {
		Pong(ctx context.Context, in *Request, out *Response) error
	}
	type Pong struct {
		pong
	}
	h := &pongHandler{hdlr}
	return s.Handle(s.NewHandler(&Pong{h}, opts...))
}

type pongHandler struct {
	PongHandler
}

func (h *pongHandler) Pong(ctx context.Context, in *Request, out *Response) error {
	return h.PongHandler.Pong(ctx, in, out)
}
