// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Healthcheck struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Healthcheck) Reset()         { *m = Healthcheck{} }
func (m *Healthcheck) String() string { return proto.CompactTextString(m) }
func (*Healthcheck) ProtoMessage()    {}
func (*Healthcheck) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{0}
}

func (m *Healthcheck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Healthcheck.Unmarshal(m, b)
}
func (m *Healthcheck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Healthcheck.Marshal(b, m, deterministic)
}
func (m *Healthcheck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Healthcheck.Merge(m, src)
}
func (m *Healthcheck) XXX_Size() int {
	return xxx_messageInfo_Healthcheck.Size(m)
}
func (m *Healthcheck) XXX_DiscardUnknown() {
	xxx_messageInfo_Healthcheck.DiscardUnknown(m)
}

var xxx_messageInfo_Healthcheck proto.InternalMessageInfo

type User struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	ProfilePictureUrl    string   `protobuf:"bytes,6,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	Admin                bool     `protobuf:"varint,7,opt,name=admin,proto3" json:"admin,omitempty"`
	FollowersCount       int32    `protobuf:"varint,8,opt,name=followers_count,json=followersCount,proto3" json:"followers_count,omitempty"`
	FollowingCount       int32    `protobuf:"varint,9,opt,name=following_count,json=followingCount,proto3" json:"following_count,omitempty"`
	PostsCount           int32    `protobuf:"varint,10,opt,name=posts_count,json=postsCount,proto3" json:"posts_count,omitempty"`
	Username             string   `protobuf:"bytes,11,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetProfilePictureUrl() string {
	if m != nil {
		return m.ProfilePictureUrl
	}
	return ""
}

func (m *User) GetAdmin() bool {
	if m != nil {
		return m.Admin
	}
	return false
}

func (m *User) GetFollowersCount() int32 {
	if m != nil {
		return m.FollowersCount
	}
	return 0
}

func (m *User) GetFollowingCount() int32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *User) GetPostsCount() int32 {
	if m != nil {
		return m.PostsCount
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

type UpdatePasswordRequest struct {
	CurrentPassword      string   `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{3}
}

func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(m, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetCurrentPassword() string {
	if m != nil {
		return m.CurrentPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type Picture struct {
	Base64               string   `protobuf:"bytes,1,opt,name=base64,proto3" json:"base64,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Picture) Reset()         { *m = Picture{} }
func (m *Picture) String() string { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()    {}
func (*Picture) Descriptor() ([]byte, []int) {
	return fileDescriptor_477cbf5ae5b46edf, []int{4}
}

func (m *Picture) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Picture.Unmarshal(m, b)
}
func (m *Picture) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Picture.Marshal(b, m, deterministic)
}
func (m *Picture) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Picture.Merge(m, src)
}
func (m *Picture) XXX_Size() int {
	return xxx_messageInfo_Picture.Size(m)
}
func (m *Picture) XXX_DiscardUnknown() {
	xxx_messageInfo_Picture.DiscardUnknown(m)
}

var xxx_messageInfo_Picture proto.InternalMessageInfo

func (m *Picture) GetBase64() string {
	if m != nil {
		return m.Base64
	}
	return ""
}

func init() {
	proto.RegisterType((*Healthcheck)(nil), "Healthcheck")
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*Response)(nil), "Response")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "UpdatePasswordRequest")
	proto.RegisterType((*Picture)(nil), "Picture")
}

func init() { proto.RegisterFile("proto/account.proto", fileDescriptor_477cbf5ae5b46edf) }

var fileDescriptor_477cbf5ae5b46edf = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xcd, 0x6e, 0xd4, 0x3c,
	0x14, 0x6d, 0x3a, 0x93, 0x4c, 0x72, 0xd3, 0xaf, 0xed, 0x77, 0x29, 0x55, 0x3a, 0x05, 0x31, 0xcd,
	0x02, 0x86, 0x05, 0x41, 0x2a, 0x7f, 0x6b, 0xc4, 0x02, 0x16, 0x08, 0x55, 0x91, 0x66, 0x1d, 0xb9,
	0x99, 0x3b, 0xd3, 0x40, 0xc6, 0x0e, 0xb6, 0xa3, 0x3c, 0x2d, 0x8f, 0xc0, 0x3b, 0xa0, 0xd8, 0x4e,
	0xdb, 0x48, 0xb3, 0xf3, 0xf9, 0xb1, 0xe3, 0x73, 0x72, 0x0d, 0x4f, 0x1a, 0x29, 0xb4, 0x78, 0xcb,
	0xca, 0x52, 0xb4, 0x5c, 0x67, 0x06, 0xa5, 0xff, 0x41, 0xfc, 0x8d, 0x58, 0xad, 0xef, 0xca, 0x3b,
	0x2a, 0x7f, 0xa5, 0x7f, 0x0e, 0x61, 0xba, 0x52, 0x24, 0x11, 0x61, 0xda, 0xb6, 0xd5, 0x3a, 0xf1,
	0x16, 0xde, 0x32, 0xca, 0xcd, 0x1a, 0x9f, 0x03, 0x6c, 0x2a, 0xa9, 0x74, 0xc1, 0xd9, 0x8e, 0x92,
	0x43, 0xa3, 0x44, 0x86, 0xf9, 0xc1, 0x76, 0x84, 0x97, 0x10, 0xd5, 0x6c, 0x50, 0x27, 0x46, 0x0d,
	0x7b, 0xc2, 0x88, 0x67, 0xe0, 0xd3, 0x8e, 0x55, 0x75, 0x32, 0x35, 0x82, 0x05, 0x38, 0x87, 0xb0,
	0x61, 0x4a, 0x75, 0x42, 0xae, 0x13, 0xdf, 0xee, 0x18, 0x30, 0x66, 0xe6, 0xc2, 0x9b, 0xaa, 0xa6,
	0xa2, 0xa9, 0x4a, 0xdd, 0x4a, 0x2a, 0x5a, 0x59, 0x27, 0x81, 0xb1, 0xfd, 0xef, 0xa4, 0x1b, 0xab,
	0xac, 0x64, 0xdd, 0x7f, 0x81, 0xad, 0x77, 0x15, 0x4f, 0x66, 0x0b, 0x6f, 0x19, 0xe6, 0x16, 0xe0,
	0x2b, 0x38, 0xd9, 0x88, 0xba, 0x16, 0x1d, 0x49, 0x55, 0x98, 0xe0, 0x49, 0xb8, 0xf0, 0x96, 0x7e,
	0x7e, 0x7c, 0x4f, 0x7f, 0xe9, 0xd9, 0x07, 0x63, 0xc5, 0xb7, 0xce, 0x18, 0x3d, 0x36, 0x56, 0x7c,
	0x6b, 0x8d, 0x2f, 0x20, 0x6e, 0x84, 0xd2, 0xc3, 0x69, 0x60, 0x4c, 0x60, 0x28, 0x6b, 0x98, 0x43,
	0xd8, 0x2a, 0x92, 0xa6, 0x86, 0xd8, 0x86, 0x1a, 0x70, 0xfa, 0x09, 0xc2, 0x9c, 0x54, 0x23, 0xb8,
	0x22, 0xbc, 0x80, 0x69, 0xcf, 0x9b, 0x8a, 0xe3, 0x6b, 0x3f, 0xeb, 0x7b, 0xcf, 0x0d, 0x85, 0xa7,
	0x30, 0xf9, 0xd9, 0x69, 0x57, 0x71, 0xbf, 0x4c, 0x09, 0x9e, 0xae, 0x9a, 0x35, 0xd3, 0x74, 0xe3,
	0xfa, 0xc9, 0xe9, 0x77, 0x4b, 0x4a, 0xe3, 0x6b, 0x38, 0x2d, 0x5b, 0x29, 0x89, 0xeb, 0xe2, 0xbe,
	0x4a, 0xfb, 0xd3, 0x4e, 0x1c, 0x3f, 0xec, 0xc0, 0x2b, 0x38, 0xe2, 0xd4, 0x3d, 0xd8, 0xec, 0xf1,
	0x31, 0xa7, 0x6e, 0xb0, 0xa4, 0x57, 0x30, 0x73, 0x95, 0xe2, 0x39, 0x04, 0xb7, 0x4c, 0xd1, 0xc7,
	0xf7, 0xee, 0x38, 0x87, 0xae, 0xff, 0x7a, 0x30, 0xfb, 0x6c, 0x67, 0x08, 0x2f, 0xc1, 0xff, 0x2e,
	0xb6, 0x15, 0x47, 0x7b, 0xfb, 0x79, 0x94, 0x0d, 0xe9, 0xd2, 0x03, 0xbc, 0x80, 0xc9, 0x57, 0xd2,
	0x7b, 0xa5, 0x67, 0x10, 0xd8, 0x34, 0x7b, 0xd5, 0x0f, 0x70, 0x3c, 0xce, 0x8a, 0xe7, 0xd9, 0xde,
	0xf0, 0xe3, 0x6d, 0x6f, 0xe0, 0xcc, 0xb9, 0x46, 0xb3, 0x81, 0x61, 0xe6, 0x56, 0x63, 0xfb, 0x4b,
	0x08, 0xec, 0xe4, 0xe3, 0x51, 0xf6, 0xe8, 0x09, 0xcc, 0x47, 0x28, 0x3d, 0xb8, 0x0d, 0xcc, 0x43,
	0x79, 0xf7, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x44, 0x81, 0xba, 0x3f, 0x03, 0x00, 0x00,
}
