# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.0"
gem "jekyll-paginate", "~> 1.1"
gem "pygments.rb", "~> 1.2"
gem "redcarpet", "~> 3.5"
gem "jekyll-gist", "~> 1.5"
gem "kramdown", "~> 2.1"
