// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/ledger.proto

package ledger

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionType int32

const (
	TransactionType_NONE       TransactionType = 0
	TransactionType_DEPOSIT    TransactionType = 1
	TransactionType_WITHDRAWAL TransactionType = 2
	TransactionType_BUY_ASSET  TransactionType = 3
	TransactionType_SELL_ASSET TransactionType = 4
)

var TransactionType_name = map[int32]string{
	0: "NONE",
	1: "DEPOSIT",
	2: "WITHDRAWAL",
	3: "BUY_ASSET",
	4: "SELL_ASSET",
}

var TransactionType_value = map[string]int32{
	"NONE":       0,
	"DEPOSIT":    1,
	"WITHDRAWAL": 2,
	"BUY_ASSET":  3,
	"SELL_ASSET": 4,
}

func (x TransactionType) String() string {
	return proto.EnumName(TransactionType_name, int32(x))
}

func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_a72d59ff9cb84a58, []int{0}
}

type Portfolio struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CurrentBalance       int64    `protobuf:"varint,2,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Portfolio) Reset()         { *m = Portfolio{} }
func (m *Portfolio) String() string { return proto.CompactTextString(m) }
func (*Portfolio) ProtoMessage()    {}
func (*Portfolio) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72d59ff9cb84a58, []int{0}
}

func (m *Portfolio) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Portfolio.Unmarshal(m, b)
}
func (m *Portfolio) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Portfolio.Marshal(b, m, deterministic)
}
func (m *Portfolio) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Portfolio.Merge(m, src)
}
func (m *Portfolio) XXX_Size() int {
	return xxx_messageInfo_Portfolio.Size(m)
}
func (m *Portfolio) XXX_DiscardUnknown() {
	xxx_messageInfo_Portfolio.DiscardUnknown(m)
}

var xxx_messageInfo_Portfolio proto.InternalMessageInfo

func (m *Portfolio) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Portfolio) GetCurrentBalance() int64 {
	if m != nil {
		return m.CurrentBalance
	}
	return 0
}

type Transaction struct {
	Uuid                 string          `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PortfolioUuid        string          `protobuf:"bytes,2,opt,name=portfolio_uuid,json=portfolioUuid,proto3" json:"portfolio_uuid,omitempty"`
	Amount               int64           `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 TransactionType `protobuf:"varint,4,opt,name=type,proto3,enum=TransactionType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_a72d59ff9cb84a58, []int{1}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Transaction) GetPortfolioUuid() string {
	if m != nil {
		return m.PortfolioUuid
	}
	return ""
}

func (m *Transaction) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetType() TransactionType {
	if m != nil {
		return m.Type
	}
	return TransactionType_NONE
}

func init() {
	proto.RegisterEnum("TransactionType", TransactionType_name, TransactionType_value)
	proto.RegisterType((*Portfolio)(nil), "Portfolio")
	proto.RegisterType((*Transaction)(nil), "Transaction")
}

func init() { proto.RegisterFile("proto/ledger.proto", fileDescriptor_a72d59ff9cb84a58) }

var fileDescriptor_a72d59ff9cb84a58 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xd1, 0x4e, 0x83, 0x30,
	0x18, 0x85, 0xd7, 0x41, 0x50, 0xfe, 0x6d, 0x0c, 0x7b, 0x61, 0xc8, 0xae, 0x08, 0xd1, 0x48, 0xbc,
	0xc0, 0x38, 0x9f, 0x80, 0x39, 0xe2, 0x96, 0x90, 0x6d, 0x01, 0x16, 0xe2, 0x15, 0xe9, 0x58, 0x35,
	0x24, 0x48, 0x49, 0x2d, 0x17, 0x7b, 0x01, 0x9f, 0xdb, 0xac, 0xe2, 0x44, 0xe3, 0xdd, 0x39, 0xe7,
	0x6b, 0x7a, 0xda, 0xff, 0x07, 0x5c, 0x73, 0x26, 0xd8, 0x5d, 0x49, 0xf7, 0xaf, 0x94, 0x7b, 0xd2,
	0x38, 0x0b, 0xd0, 0x37, 0x8c, 0x8b, 0x17, 0x56, 0x16, 0x0c, 0x63, 0x50, 0x9b, 0xa6, 0xd8, 0x5b,
	0xc8, 0x46, 0xae, 0x1e, 0x49, 0x8d, 0x6f, 0x60, 0x9c, 0x37, 0x9c, 0xd3, 0x4a, 0x64, 0x3b, 0x52,
	0x92, 0x2a, 0xa7, 0x56, 0xdf, 0x46, 0xae, 0x12, 0x19, 0x6d, 0x3c, 0xfb, 0x4a, 0x9d, 0x0f, 0x04,
	0x83, 0x84, 0x93, 0xea, 0x9d, 0xe4, 0xa2, 0x60, 0xd5, 0xbf, 0x97, 0x5d, 0x83, 0x51, 0x7f, 0xb7,
	0x65, 0x92, 0xf6, 0x25, 0x1d, 0x9d, 0xd2, 0xed, 0xf1, 0xd8, 0x25, 0x68, 0xe4, 0x8d, 0x35, 0x95,
	0xb0, 0x14, 0x59, 0xd5, 0x3a, 0x7c, 0x05, 0xaa, 0x38, 0xd4, 0xd4, 0x52, 0x6d, 0xe4, 0x1a, 0x53,
	0xd3, 0xeb, 0xd4, 0x25, 0x87, 0x9a, 0x46, 0x92, 0xde, 0xa6, 0x30, 0xfe, 0x03, 0xf0, 0x39, 0xa8,
	0xab, 0xf5, 0x2a, 0x30, 0x7b, 0x78, 0x00, 0x67, 0xf3, 0x60, 0xb3, 0x8e, 0x97, 0x89, 0x89, 0xb0,
	0x01, 0x90, 0x2e, 0x93, 0xc5, 0x3c, 0xf2, 0x53, 0x3f, 0x34, 0xfb, 0x78, 0x04, 0xfa, 0x6c, 0xfb,
	0x9c, 0xf9, 0x71, 0x1c, 0x24, 0xa6, 0x72, 0xc4, 0x71, 0x10, 0x86, 0xad, 0x57, 0xa7, 0x14, 0xb4,
	0x50, 0xce, 0x0e, 0xdf, 0xc3, 0xc5, 0x23, 0xa7, 0x44, 0xd0, 0xee, 0x87, 0x87, 0xdd, 0xf7, 0x4c,
	0x7e, 0x39, 0xa7, 0x87, 0x5d, 0x18, 0x3e, 0x51, 0xf1, 0x33, 0x6b, 0xf0, 0x4e, 0x7a, 0xd2, 0xd1,
	0x4e, 0x6f, 0xa7, 0xc9, 0xcd, 0x3c, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xff, 0x36, 0x2f, 0x9d,
	0xaf, 0x01, 0x00, 0x00,
}
