// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/alert/alert.proto

package alert

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Event is inspired by Google Analytics events
// https://developers.google.com/analytics/devguides/collection/analyticsjs/events
type Event struct {
	// id is not required for inserts
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Category             string            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Action               string            `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Label                string            `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	Value                uint64            `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c479e69da88225b, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Event) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Event) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type ReportEventRequest struct {
	Event                *Event   `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportEventRequest) Reset()         { *m = ReportEventRequest{} }
func (m *ReportEventRequest) String() string { return proto.CompactTextString(m) }
func (*ReportEventRequest) ProtoMessage()    {}
func (*ReportEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c479e69da88225b, []int{1}
}

func (m *ReportEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEventRequest.Unmarshal(m, b)
}
func (m *ReportEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEventRequest.Marshal(b, m, deterministic)
}
func (m *ReportEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEventRequest.Merge(m, src)
}
func (m *ReportEventRequest) XXX_Size() int {
	return xxx_messageInfo_ReportEventRequest.Size(m)
}
func (m *ReportEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEventRequest proto.InternalMessageInfo

func (m *ReportEventRequest) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type ReportEventResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportEventResponse) Reset()         { *m = ReportEventResponse{} }
func (m *ReportEventResponse) String() string { return proto.CompactTextString(m) }
func (*ReportEventResponse) ProtoMessage()    {}
func (*ReportEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c479e69da88225b, []int{2}
}

func (m *ReportEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportEventResponse.Unmarshal(m, b)
}
func (m *ReportEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportEventResponse.Marshal(b, m, deterministic)
}
func (m *ReportEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportEventResponse.Merge(m, src)
}
func (m *ReportEventResponse) XXX_Size() int {
	return xxx_messageInfo_ReportEventResponse.Size(m)
}
func (m *ReportEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportEventResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Event)(nil), "alert.Event")
	proto.RegisterMapType((map[string]string)(nil), "alert.Event.MetadataEntry")
	proto.RegisterType((*ReportEventRequest)(nil), "alert.ReportEventRequest")
	proto.RegisterType((*ReportEventResponse)(nil), "alert.ReportEventResponse")
}

func init() { proto.RegisterFile("proto/alert/alert.proto", fileDescriptor_2c479e69da88225b) }

var fileDescriptor_2c479e69da88225b = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xd2, 0x0d, 0x75, 0xa2, 0x22, 0xe3, 0xbf, 0x35, 0xa7, 0x90, 0x53, 0x4e, 0x11,
	0x22, 0x48, 0xd1, 0x93, 0x87, 0x7a, 0x13, 0x61, 0xbf, 0xc1, 0xb6, 0x19, 0x24, 0x18, 0xb3, 0x31,
	0x99, 0x16, 0xf2, 0x9d, 0xfd, 0x10, 0x92, 0xdd, 0x50, 0x5b, 0xf4, 0xb2, 0xec, 0xef, 0xbd, 0xd9,
	0x79, 0x0f, 0x16, 0x6e, 0xda, 0xce, 0xb0, 0xb9, 0xd3, 0x35, 0x75, 0xec, 0xce, 0xdc, 0x2a, 0x28,
	0x2c, 0xa4, 0xdf, 0x1e, 0x88, 0xe5, 0x96, 0x1a, 0xc6, 0x33, 0xf0, 0xab, 0x52, 0x7a, 0x89, 0x97,
	0x1d, 0x2b, 0xbf, 0x2a, 0x31, 0x86, 0xf9, 0x5a, 0x33, 0xbd, 0x9b, 0x6e, 0x90, 0xbe, 0x55, 0x77,
	0x8c, 0xd7, 0x10, 0xea, 0x35, 0x57, 0xa6, 0x91, 0x81, 0x75, 0x26, 0xc2, 0x4b, 0x10, 0xb5, 0x5e,
	0x51, 0x2d, 0x67, 0x56, 0x76, 0x30, 0xaa, 0x5b, 0x5d, 0x6f, 0x48, 0x8a, 0xc4, 0xcb, 0x66, 0xca,
	0x01, 0x3e, 0xc0, 0xfc, 0x93, 0x58, 0x97, 0x9a, 0xb5, 0x0c, 0x93, 0x20, 0x8b, 0x8a, 0x38, 0x77,
	0x05, 0x6d, 0x9f, 0xfc, 0x75, 0x32, 0x97, 0x0d, 0x77, 0x83, 0xda, 0xcd, 0xc6, 0x4f, 0x70, 0x7a,
	0x60, 0xe1, 0x39, 0x04, 0x1f, 0x34, 0x4c, 0xcd, 0xc7, 0xeb, 0x6f, 0xa0, 0xeb, 0xed, 0xe0, 0xd1,
	0x5f, 0x78, 0xe9, 0x02, 0x50, 0x51, 0x6b, 0x3a, 0xb6, 0x19, 0x8a, 0xbe, 0x36, 0xd4, 0x33, 0xa6,
	0x20, 0x68, 0x64, 0xbb, 0x23, 0x2a, 0x4e, 0xf6, 0x7b, 0x28, 0x67, 0xa5, 0x57, 0x70, 0x71, 0xf0,
	0xb2, 0x6f, 0x4d, 0xd3, 0x53, 0xf1, 0x06, 0xe2, 0x79, 0x1c, 0xc6, 0x17, 0x88, 0xf6, 0x7c, 0xbc,
	0x9d, 0x76, 0xfc, 0x4d, 0x8b, 0xe3, 0xff, 0x2c, 0xb7, 0x2e, 0x3d, 0x5a, 0x85, 0xf6, 0x7b, 0xee,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x01, 0x62, 0x3c, 0xb9, 0x01, 0x00, 0x00,
}
