// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/micro/services/users/api/proto/users.proto

package go_micro_api_users

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ReadRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{1}
}

func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (m *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(m, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

type ReadResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{2}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{3}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{4}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{5}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

type DeleteResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c19a6b5ea214fa78, []int{6}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.api.users.User")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.api.users.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.api.users.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.api.users.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.api.users.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.api.users.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.api.users.DeleteResponse")
}

func init() {
	proto.RegisterFile("github.com/micro/services/users/api/proto/users.proto", fileDescriptor_c19a6b5ea214fa78)
}

var fileDescriptor_c19a6b5ea214fa78 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xda, 0xb4, 0xda, 0xa9, 0xad, 0xb0, 0x78, 0x08, 0x15, 0xb1, 0xee, 0xa9, 0x07, 0xd9,
	0x40, 0xc5, 0x9b, 0x7a, 0xf2, 0x26, 0x08, 0x06, 0x7a, 0x96, 0x6d, 0x32, 0xd6, 0x85, 0xa6, 0x1b,
	0x77, 0x13, 0xbf, 0xc6, 0x2f, 0xf5, 0x24, 0x3b, 0xdb, 0x48, 0x8b, 0x51, 0xb0, 0xb7, 0xbc, 0x79,
	0x33, 0x6f, 0xdf, 0x7b, 0x04, 0xae, 0x97, 0xaa, 0x7c, 0xad, 0x16, 0x22, 0xd5, 0x79, 0x9c, 0xab,
	0xd4, 0xe8, 0xd8, 0xa2, 0x79, 0x57, 0x29, 0xda, 0xb8, 0xb2, 0x68, 0x6c, 0x2c, 0x0b, 0x15, 0x17,
	0x46, 0x97, 0xda, 0x63, 0x41, 0xdf, 0x8c, 0x2d, 0xb5, 0xa0, 0x75, 0x21, 0x0b, 0x25, 0x88, 0xe1,
	0x1f, 0x01, 0x84, 0x73, 0x8b, 0x86, 0x8d, 0xa0, 0xad, 0xb2, 0x28, 0x98, 0x04, 0xd3, 0x7e, 0xd2,
	0x56, 0x19, 0x8b, 0xe0, 0x20, 0x35, 0x28, 0x4b, 0xcc, 0xa2, 0xf6, 0x24, 0x98, 0x76, 0x92, 0x1a,
	0x3a, 0xa6, 0x2a, 0x32, 0x62, 0x3a, 0x9e, 0xd9, 0x40, 0x76, 0x06, 0xf0, 0xa2, 0x8c, 0x2d, 0x9f,
	0xd7, 0x32, 0xc7, 0x28, 0x24, 0xad, 0x3e, 0x4d, 0x1e, 0x65, 0x8e, 0xec, 0x14, 0xfa, 0x2b, 0x59,
	0xb3, 0x5d, 0x62, 0x0f, 0xdd, 0x80, 0xc8, 0x13, 0xe8, 0x62, 0x2e, 0xd5, 0x2a, 0xea, 0x11, 0xe1,
	0x01, 0x1f, 0xc2, 0x20, 0x41, 0x99, 0x25, 0xf8, 0x56, 0xa1, 0x2d, 0xf9, 0x0d, 0x1c, 0x79, 0x68,
	0x0b, 0xbd, 0xb6, 0xc8, 0x2e, 0x21, 0x74, 0x31, 0xc8, 0xf6, 0x60, 0x16, 0x89, 0x9f, 0x01, 0x85,
	0x0b, 0x97, 0xd0, 0x16, 0xbf, 0x85, 0xe1, 0x9c, 0x9c, 0x6e, 0xe4, 0xfe, 0x79, 0x7e, 0x07, 0xa3,
	0xfa, 0x7c, 0xaf, 0xe7, 0x8f, 0x61, 0x78, 0x8f, 0x2b, 0xfc, 0x7e, 0xde, 0x09, 0xd6, 0x83, 0x7d,
	0x04, 0x67, 0x9f, 0x01, 0x74, 0x1d, 0xb4, 0xec, 0x01, 0x42, 0xd7, 0x0b, 0x3b, 0x6f, 0xba, 0xd8,
	0x2a, 0x70, 0x3c, 0xf9, 0x7d, 0xc1, 0x5b, 0xe0, 0x2d, 0xf6, 0x04, 0x3d, 0x9f, 0x93, 0x5d, 0x34,
	0x1a, 0xd8, 0xae, 0x70, 0xcc, 0xff, 0x5a, 0xd9, 0x96, 0xf4, 0x49, 0x9b, 0x25, 0x77, 0x6a, 0x69,
	0x96, 0xdc, 0x2d, 0x8a, 0xb7, 0x16, 0x3d, 0xfa, 0xa7, 0xaf, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x5b, 0xce, 0x45, 0x4d, 0x0c, 0x03, 0x00, 0x00,
}
