// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/stock-quote.proto

package stock_quote

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Stock struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	IncludeOutOfHours    bool     `protobuf:"varint,2,opt,name=include_out_of_hours,json=includeOutOfHours,proto3" json:"include_out_of_hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stock) Reset()         { *m = Stock{} }
func (m *Stock) String() string { return proto.CompactTextString(m) }
func (*Stock) ProtoMessage()    {}
func (*Stock) Descriptor() ([]byte, []int) {
	return fileDescriptor_df9fd68db6092168, []int{0}
}

func (m *Stock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stock.Unmarshal(m, b)
}
func (m *Stock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stock.Marshal(b, m, deterministic)
}
func (m *Stock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stock.Merge(m, src)
}
func (m *Stock) XXX_Size() int {
	return xxx_messageInfo_Stock.Size(m)
}
func (m *Stock) XXX_DiscardUnknown() {
	xxx_messageInfo_Stock.DiscardUnknown(m)
}

var xxx_messageInfo_Stock proto.InternalMessageInfo

func (m *Stock) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Stock) GetIncludeOutOfHours() bool {
	if m != nil {
		return m.IncludeOutOfHours
	}
	return false
}

type Quote struct {
	StockUuid            string   `protobuf:"bytes,1,opt,name=stock_uuid,json=stockUuid,proto3" json:"stock_uuid,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	PercentageChange     float32  `protobuf:"fixed32,3,opt,name=percentage_change,json=percentageChange,proto3" json:"percentage_change,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	MarketClosed         bool     `protobuf:"varint,5,opt,name=market_closed,json=marketClosed,proto3" json:"market_closed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Quote) Reset()         { *m = Quote{} }
func (m *Quote) String() string { return proto.CompactTextString(m) }
func (*Quote) ProtoMessage()    {}
func (*Quote) Descriptor() ([]byte, []int) {
	return fileDescriptor_df9fd68db6092168, []int{1}
}

func (m *Quote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quote.Unmarshal(m, b)
}
func (m *Quote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quote.Marshal(b, m, deterministic)
}
func (m *Quote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quote.Merge(m, src)
}
func (m *Quote) XXX_Size() int {
	return xxx_messageInfo_Quote.Size(m)
}
func (m *Quote) XXX_DiscardUnknown() {
	xxx_messageInfo_Quote.DiscardUnknown(m)
}

var xxx_messageInfo_Quote proto.InternalMessageInfo

func (m *Quote) GetStockUuid() string {
	if m != nil {
		return m.StockUuid
	}
	return ""
}

func (m *Quote) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Quote) GetPercentageChange() float32 {
	if m != nil {
		return m.PercentageChange
	}
	return 0
}

func (m *Quote) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Quote) GetMarketClosed() bool {
	if m != nil {
		return m.MarketClosed
	}
	return false
}

type ListRequest struct {
	Uuids                []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	IncludeOutOfHours    bool     `protobuf:"varint,2,opt,name=include_out_of_hours,json=includeOutOfHours,proto3" json:"include_out_of_hours,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df9fd68db6092168, []int{2}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUuids() []string {
	if m != nil {
		return m.Uuids
	}
	return nil
}

func (m *ListRequest) GetIncludeOutOfHours() bool {
	if m != nil {
		return m.IncludeOutOfHours
	}
	return false
}

type ListResponse struct {
	Quotes               []*Quote `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df9fd68db6092168, []int{3}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetQuotes() []*Quote {
	if m != nil {
		return m.Quotes
	}
	return nil
}

func init() {
	proto.RegisterType((*Stock)(nil), "Stock")
	proto.RegisterType((*Quote)(nil), "Quote")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
}

func init() { proto.RegisterFile("proto/stock-quote.proto", fileDescriptor_df9fd68db6092168) }

var fileDescriptor_df9fd68db6092168 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x6b, 0xea, 0x40,
	0x10, 0xc7, 0x8d, 0x9a, 0x60, 0x46, 0x85, 0xe7, 0x22, 0xbc, 0x20, 0xef, 0x95, 0x90, 0x5e, 0x02,
	0xd2, 0x08, 0xf6, 0x13, 0x14, 0x0f, 0xed, 0x41, 0x90, 0xa6, 0x2d, 0x3d, 0x2e, 0xe9, 0x66, 0xd4,
	0xa0, 0xcd, 0xc6, 0xec, 0xee, 0xc7, 0xea, 0x77, 0x2c, 0x3b, 0x1b, 0xa8, 0xd7, 0xde, 0x76, 0x7e,
	0xc3, 0xfe, 0x66, 0xf8, 0x0f, 0xfc, 0x6d, 0x5a, 0xa9, 0xe5, 0x4a, 0x69, 0x29, 0x4e, 0x77, 0x17,
	0x23, 0x35, 0x66, 0x44, 0x92, 0x2d, 0xf8, 0x2f, 0x16, 0x32, 0x06, 0x43, 0x63, 0xaa, 0x32, 0xf2,
	0x62, 0x2f, 0x0d, 0x73, 0x7a, 0xb3, 0x15, 0xcc, 0xab, 0x5a, 0x9c, 0x4d, 0x89, 0x5c, 0x1a, 0xcd,
	0xe5, 0x9e, 0x1f, 0xa5, 0x69, 0x55, 0xd4, 0x8f, 0xbd, 0x74, 0x94, 0xcf, 0xba, 0xde, 0xce, 0xe8,
	0xdd, 0xfe, 0xc9, 0x36, 0x92, 0x2f, 0x0f, 0xfc, 0x67, 0x6b, 0x67, 0xff, 0x01, 0x68, 0x18, 0xbf,
	0x92, 0x86, 0x44, 0xde, 0xac, 0x79, 0x0e, 0x7e, 0xd3, 0x56, 0x02, 0x49, 0x35, 0xc8, 0x5d, 0xc1,
	0x96, 0x30, 0x6b, 0xb0, 0x15, 0x58, 0xeb, 0xe2, 0x80, 0x5c, 0x1c, 0x8b, 0xfa, 0x80, 0xd1, 0x20,
	0xf6, 0xd2, 0x7e, 0xfe, 0xe7, 0xa7, 0xb1, 0x21, 0x6e, 0x27, 0x88, 0x16, 0x0b, 0x8d, 0x25, 0x2f,
	0x74, 0x34, 0x24, 0x4f, 0xd8, 0x91, 0x07, 0xcd, 0x6e, 0x61, 0xfa, 0x59, 0xb4, 0x27, 0xd4, 0x5c,
	0x9c, 0xa5, 0xc2, 0x32, 0xf2, 0x69, 0xe9, 0x89, 0x83, 0x1b, 0x62, 0xc9, 0x2b, 0x8c, 0xb7, 0x95,
	0xd2, 0x39, 0x5e, 0x0c, 0x2a, 0x6d, 0xb7, 0xb2, 0xeb, 0xaa, 0xc8, 0x8b, 0x07, 0x69, 0x98, 0xbb,
	0xe2, 0xf7, 0x29, 0x64, 0x30, 0x71, 0x56, 0xd5, 0xc8, 0x5a, 0x21, 0xbb, 0x81, 0x80, 0x22, 0x77,
	0xde, 0xf1, 0x3a, 0xc8, 0x28, 0xa3, 0xbc, 0xa3, 0xeb, 0x77, 0x00, 0xba, 0x81, 0x4b, 0xee, 0x1f,
	0x8c, 0x1e, 0x51, 0xbb, 0x77, 0x90, 0x51, 0x63, 0xd1, 0xfd, 0x48, 0x7a, 0x6c, 0x09, 0x60, 0xdd,
	0x54, 0x2a, 0x36, 0xc9, 0xae, 0xd6, 0x5f, 0x4c, 0xb3, 0xeb, 0xb1, 0x49, 0xef, 0x23, 0xa0, 0x1b,
	0xdf, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x2c, 0x14, 0xa2, 0xfe, 0x01, 0x00, 0x00,
}
