// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/push-notifications.proto

package push_notifications

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserUuid             string   `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb56df61812d9c2, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

type Notification struct {
	UserUuid             string   `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle             string   `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcb56df61812d9c2, []int{1}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetUserUuid() string {
	if m != nil {
		return m.UserUuid
	}
	return ""
}

func (m *Notification) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Notification) GetSubtitle() string {
	if m != nil {
		return m.Subtitle
	}
	return ""
}

func init() {
	proto.RegisterType((*Token)(nil), "Token")
	proto.RegisterType((*Notification)(nil), "Notification")
}

func init() { proto.RegisterFile("proto/push-notifications.proto", fileDescriptor_fcb56df61812d9c2) }

var fileDescriptor_fcb56df61812d9c2 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x28, 0x2d, 0xce, 0xd0, 0xcd, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c,
	0xc9, 0xcc, 0xcf, 0x2b, 0xd6, 0x03, 0x4b, 0x28, 0x59, 0x71, 0xb1, 0x86, 0xe4, 0x67, 0xa7, 0xe6,
	0x09, 0x89, 0x70, 0xb1, 0x96, 0x80, 0x18, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e,
	0x90, 0x34, 0x17, 0x67, 0x69, 0x71, 0x6a, 0x51, 0x7c, 0x69, 0x69, 0x66, 0x8a, 0x04, 0x13, 0x58,
	0x86, 0x03, 0x24, 0x10, 0x5a, 0x9a, 0x99, 0xa2, 0x14, 0xcb, 0xc5, 0xe3, 0x87, 0x64, 0x24, 0xaa,
	0x62, 0x46, 0x54, 0xc5, 0x60, 0xf3, 0x33, 0x4b, 0x72, 0x52, 0xa1, 0xa6, 0x40, 0x38, 0x42, 0x52,
	0x5c, 0x1c, 0xc5, 0xa5, 0x49, 0x10, 0x09, 0x66, 0x88, 0x0e, 0x18, 0xdf, 0x28, 0x8b, 0x4b, 0x30,
	0xa0, 0xb4, 0x38, 0x03, 0xd9, 0x8a, 0x62, 0x21, 0x45, 0x2e, 0xde, 0xa0, 0xd4, 0xf4, 0xcc, 0xe2,
	0x92, 0xd4, 0x22, 0x88, 0xbb, 0xd9, 0xf4, 0xc0, 0xb4, 0x14, 0x94, 0x56, 0x62, 0x10, 0x32, 0xe2,
	0x12, 0x08, 0x4e, 0xcd, 0x4b, 0x41, 0x71, 0x1a, 0xaf, 0x1e, 0x32, 0x57, 0x0a, 0x95, 0xab, 0xc4,
	0x90, 0xc4, 0x06, 0x0e, 0x0d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xc0, 0x72, 0x64,
	0x2f, 0x01, 0x00, 0x00,
}
