// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/account/account.proto

package go_micro_api_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{0}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SignupRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type SignupResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Secret               *Token   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{1}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SignupResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *SignupResponse) GetSecret() *Token {
	if m != nil {
		return m.Secret
	}
	return nil
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{2}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Token                *Token   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Secret               *Token   `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *LoginResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *LoginResponse) GetSecret() *Token {
	if m != nil {
		return m.Secret
	}
	return nil
}

type Plan struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Interval             string   `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{4}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Plan) GetInterval() string {
	if m != nil {
		return m.Interval
	}
	return ""
}

type Subscription struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Plan                 *Plan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Subscription) Reset()         { *m = Subscription{} }
func (m *Subscription) String() string { return proto.CompactTextString(m) }
func (*Subscription) ProtoMessage()    {}
func (*Subscription) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{5}
}

func (m *Subscription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Subscription.Unmarshal(m, b)
}
func (m *Subscription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Subscription.Marshal(b, m, deterministic)
}
func (m *Subscription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subscription.Merge(m, src)
}
func (m *Subscription) XXX_Size() int {
	return xxx_messageInfo_Subscription.Size(m)
}
func (m *Subscription) XXX_DiscardUnknown() {
	xxx_messageInfo_Subscription.DiscardUnknown(m)
}

var xxx_messageInfo_Subscription proto.InternalMessageInfo

func (m *Subscription) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Subscription) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expires              int64    `protobuf:"varint,2,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{6}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

type User struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64            `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64            `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	FirstName            string           `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string           `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string           `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Username             string           `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
	PaymentMethods       []*PaymentMethod `protobuf:"bytes,8,rep,name=payment_methods,json=paymentMethods,proto3" json:"payment_methods,omitempty"`
	Subscriptions        []*Subscription  `protobuf:"bytes,9,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Roles                []string         `protobuf:"bytes,10,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{7}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *User) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPaymentMethods() []*PaymentMethod {
	if m != nil {
		return m.PaymentMethods
	}
	return nil
}

func (m *User) GetSubscriptions() []*Subscription {
	if m != nil {
		return m.Subscriptions
	}
	return nil
}

func (m *User) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type ReadUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{8}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{9}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{10}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{11}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{12}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{13}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type PaymentMethod struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	CardBrand            string   `protobuf:"bytes,5,opt,name=card_brand,json=cardBrand,proto3" json:"card_brand,omitempty"`
	CardExpMonth         string   `protobuf:"bytes,6,opt,name=card_exp_month,json=cardExpMonth,proto3" json:"card_exp_month,omitempty"`
	CardExpYear          string   `protobuf:"bytes,7,opt,name=card_exp_year,json=cardExpYear,proto3" json:"card_exp_year,omitempty"`
	CardLast_4           string   `protobuf:"bytes,8,opt,name=card_last_4,json=cardLast4,proto3" json:"card_last_4,omitempty"`
	Default              bool     `protobuf:"varint,9,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentMethod) Reset()         { *m = PaymentMethod{} }
func (m *PaymentMethod) String() string { return proto.CompactTextString(m) }
func (*PaymentMethod) ProtoMessage()    {}
func (*PaymentMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{14}
}

func (m *PaymentMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentMethod.Unmarshal(m, b)
}
func (m *PaymentMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentMethod.Marshal(b, m, deterministic)
}
func (m *PaymentMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentMethod.Merge(m, src)
}
func (m *PaymentMethod) XXX_Size() int {
	return xxx_messageInfo_PaymentMethod.Size(m)
}
func (m *PaymentMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentMethod.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentMethod proto.InternalMessageInfo

func (m *PaymentMethod) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PaymentMethod) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *PaymentMethod) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PaymentMethod) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *PaymentMethod) GetCardBrand() string {
	if m != nil {
		return m.CardBrand
	}
	return ""
}

func (m *PaymentMethod) GetCardExpMonth() string {
	if m != nil {
		return m.CardExpMonth
	}
	return ""
}

func (m *PaymentMethod) GetCardExpYear() string {
	if m != nil {
		return m.CardExpYear
	}
	return ""
}

func (m *PaymentMethod) GetCardLast_4() string {
	if m != nil {
		return m.CardLast_4
	}
	return ""
}

func (m *PaymentMethod) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

type CreatePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePaymentMethodRequest) Reset()         { *m = CreatePaymentMethodRequest{} }
func (m *CreatePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodRequest) ProtoMessage()    {}
func (*CreatePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{15}
}

func (m *CreatePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodRequest.Unmarshal(m, b)
}
func (m *CreatePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodRequest.Merge(m, src)
}
func (m *CreatePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodRequest.Size(m)
}
func (m *CreatePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodRequest proto.InternalMessageInfo

func (m *CreatePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodRequest) Reset()         { *m = DeletePaymentMethodRequest{} }
func (m *DeletePaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodRequest) ProtoMessage()    {}
func (*DeletePaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{16}
}

func (m *DeletePaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodRequest.Unmarshal(m, b)
}
func (m *DeletePaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodRequest.Merge(m, src)
}
func (m *DeletePaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodRequest.Size(m)
}
func (m *DeletePaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodRequest proto.InternalMessageInfo

func (m *DeletePaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreatePaymentMethodResponse struct {
	PaymentMethod        *PaymentMethod `protobuf:"bytes,1,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CreatePaymentMethodResponse) Reset()         { *m = CreatePaymentMethodResponse{} }
func (m *CreatePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePaymentMethodResponse) ProtoMessage()    {}
func (*CreatePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{17}
}

func (m *CreatePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePaymentMethodResponse.Unmarshal(m, b)
}
func (m *CreatePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePaymentMethodResponse.Merge(m, src)
}
func (m *CreatePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePaymentMethodResponse.Size(m)
}
func (m *CreatePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePaymentMethodResponse proto.InternalMessageInfo

func (m *CreatePaymentMethodResponse) GetPaymentMethod() *PaymentMethod {
	if m != nil {
		return m.PaymentMethod
	}
	return nil
}

type DeletePaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePaymentMethodResponse) Reset()         { *m = DeletePaymentMethodResponse{} }
func (m *DeletePaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePaymentMethodResponse) ProtoMessage()    {}
func (*DeletePaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{18}
}

func (m *DeletePaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePaymentMethodResponse.Unmarshal(m, b)
}
func (m *DeletePaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePaymentMethodResponse.Merge(m, src)
}
func (m *DeletePaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePaymentMethodResponse.Size(m)
}
func (m *DeletePaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePaymentMethodResponse proto.InternalMessageInfo

type RefreshTokenRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRequest) Reset()         { *m = RefreshTokenRequest{} }
func (m *RefreshTokenRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRequest) ProtoMessage()    {}
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{19}
}

func (m *RefreshTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRequest.Unmarshal(m, b)
}
func (m *RefreshTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRequest.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRequest.Merge(m, src)
}
func (m *RefreshTokenRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRequest.Size(m)
}
func (m *RefreshTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRequest proto.InternalMessageInfo

func (m *RefreshTokenRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type RefreshTokenResponse struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenResponse) Reset()         { *m = RefreshTokenResponse{} }
func (m *RefreshTokenResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenResponse) ProtoMessage()    {}
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{20}
}

func (m *RefreshTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenResponse.Unmarshal(m, b)
}
func (m *RefreshTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenResponse.Marshal(b, m, deterministic)
}
func (m *RefreshTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenResponse.Merge(m, src)
}
func (m *RefreshTokenResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenResponse.Size(m)
}
func (m *RefreshTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenResponse proto.InternalMessageInfo

func (m *RefreshTokenResponse) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type DefaultPaymentMethodRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultPaymentMethodRequest) Reset()         { *m = DefaultPaymentMethodRequest{} }
func (m *DefaultPaymentMethodRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultPaymentMethodRequest) ProtoMessage()    {}
func (*DefaultPaymentMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{21}
}

func (m *DefaultPaymentMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Unmarshal(m, b)
}
func (m *DefaultPaymentMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Marshal(b, m, deterministic)
}
func (m *DefaultPaymentMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultPaymentMethodRequest.Merge(m, src)
}
func (m *DefaultPaymentMethodRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultPaymentMethodRequest.Size(m)
}
func (m *DefaultPaymentMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultPaymentMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultPaymentMethodRequest proto.InternalMessageInfo

func (m *DefaultPaymentMethodRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DefaultPaymentMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultPaymentMethodResponse) Reset()         { *m = DefaultPaymentMethodResponse{} }
func (m *DefaultPaymentMethodResponse) String() string { return proto.CompactTextString(m) }
func (*DefaultPaymentMethodResponse) ProtoMessage()    {}
func (*DefaultPaymentMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{22}
}

func (m *DefaultPaymentMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Unmarshal(m, b)
}
func (m *DefaultPaymentMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Marshal(b, m, deterministic)
}
func (m *DefaultPaymentMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultPaymentMethodResponse.Merge(m, src)
}
func (m *DefaultPaymentMethodResponse) XXX_Size() int {
	return xxx_messageInfo_DefaultPaymentMethodResponse.Size(m)
}
func (m *DefaultPaymentMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultPaymentMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultPaymentMethodResponse proto.InternalMessageInfo

type CreateSubscriptionRequest struct {
	PlanId               string   `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionRequest) Reset()         { *m = CreateSubscriptionRequest{} }
func (m *CreateSubscriptionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionRequest) ProtoMessage()    {}
func (*CreateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{23}
}

func (m *CreateSubscriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionRequest.Unmarshal(m, b)
}
func (m *CreateSubscriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionRequest.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionRequest.Merge(m, src)
}
func (m *CreateSubscriptionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionRequest.Size(m)
}
func (m *CreateSubscriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionRequest proto.InternalMessageInfo

func (m *CreateSubscriptionRequest) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type CreateSubscriptionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSubscriptionResponse) Reset()         { *m = CreateSubscriptionResponse{} }
func (m *CreateSubscriptionResponse) String() string { return proto.CompactTextString(m) }
func (*CreateSubscriptionResponse) ProtoMessage()    {}
func (*CreateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{24}
}

func (m *CreateSubscriptionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSubscriptionResponse.Unmarshal(m, b)
}
func (m *CreateSubscriptionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSubscriptionResponse.Marshal(b, m, deterministic)
}
func (m *CreateSubscriptionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSubscriptionResponse.Merge(m, src)
}
func (m *CreateSubscriptionResponse) XXX_Size() int {
	return xxx_messageInfo_CreateSubscriptionResponse.Size(m)
}
func (m *CreateSubscriptionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSubscriptionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSubscriptionResponse proto.InternalMessageInfo

type ListPlansRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlansRequest) Reset()         { *m = ListPlansRequest{} }
func (m *ListPlansRequest) String() string { return proto.CompactTextString(m) }
func (*ListPlansRequest) ProtoMessage()    {}
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{25}
}

func (m *ListPlansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlansRequest.Unmarshal(m, b)
}
func (m *ListPlansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlansRequest.Marshal(b, m, deterministic)
}
func (m *ListPlansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlansRequest.Merge(m, src)
}
func (m *ListPlansRequest) XXX_Size() int {
	return xxx_messageInfo_ListPlansRequest.Size(m)
}
func (m *ListPlansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlansRequest proto.InternalMessageInfo

type ListPlansResponse struct {
	Plans                []*Plan  `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPlansResponse) Reset()         { *m = ListPlansResponse{} }
func (m *ListPlansResponse) String() string { return proto.CompactTextString(m) }
func (*ListPlansResponse) ProtoMessage()    {}
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d492a0187472a3b, []int{26}
}

func (m *ListPlansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPlansResponse.Unmarshal(m, b)
}
func (m *ListPlansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPlansResponse.Marshal(b, m, deterministic)
}
func (m *ListPlansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPlansResponse.Merge(m, src)
}
func (m *ListPlansResponse) XXX_Size() int {
	return xxx_messageInfo_ListPlansResponse.Size(m)
}
func (m *ListPlansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPlansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPlansResponse proto.InternalMessageInfo

func (m *ListPlansResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "go.micro.api.account.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "go.micro.api.account.SignupResponse")
	proto.RegisterType((*LoginRequest)(nil), "go.micro.api.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.api.account.LoginResponse")
	proto.RegisterType((*Plan)(nil), "go.micro.api.account.Plan")
	proto.RegisterType((*Subscription)(nil), "go.micro.api.account.Subscription")
	proto.RegisterType((*Token)(nil), "go.micro.api.account.Token")
	proto.RegisterType((*User)(nil), "go.micro.api.account.User")
	proto.RegisterType((*ReadUserRequest)(nil), "go.micro.api.account.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "go.micro.api.account.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "go.micro.api.account.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "go.micro.api.account.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "go.micro.api.account.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "go.micro.api.account.DeleteUserResponse")
	proto.RegisterType((*PaymentMethod)(nil), "go.micro.api.account.PaymentMethod")
	proto.RegisterType((*CreatePaymentMethodRequest)(nil), "go.micro.api.account.CreatePaymentMethodRequest")
	proto.RegisterType((*DeletePaymentMethodRequest)(nil), "go.micro.api.account.DeletePaymentMethodRequest")
	proto.RegisterType((*CreatePaymentMethodResponse)(nil), "go.micro.api.account.CreatePaymentMethodResponse")
	proto.RegisterType((*DeletePaymentMethodResponse)(nil), "go.micro.api.account.DeletePaymentMethodResponse")
	proto.RegisterType((*RefreshTokenRequest)(nil), "go.micro.api.account.RefreshTokenRequest")
	proto.RegisterType((*RefreshTokenResponse)(nil), "go.micro.api.account.RefreshTokenResponse")
	proto.RegisterType((*DefaultPaymentMethodRequest)(nil), "go.micro.api.account.DefaultPaymentMethodRequest")
	proto.RegisterType((*DefaultPaymentMethodResponse)(nil), "go.micro.api.account.DefaultPaymentMethodResponse")
	proto.RegisterType((*CreateSubscriptionRequest)(nil), "go.micro.api.account.CreateSubscriptionRequest")
	proto.RegisterType((*CreateSubscriptionResponse)(nil), "go.micro.api.account.CreateSubscriptionResponse")
	proto.RegisterType((*ListPlansRequest)(nil), "go.micro.api.account.ListPlansRequest")
	proto.RegisterType((*ListPlansResponse)(nil), "go.micro.api.account.ListPlansResponse")
}

func init() { proto.RegisterFile("proto/account/account.proto", fileDescriptor_5d492a0187472a3b) }

var fileDescriptor_5d492a0187472a3b = []byte{
	// 978 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcb, 0x6e, 0xdb, 0x46,
	0x14, 0xb5, 0xde, 0xe2, 0xb5, 0xa5, 0xc4, 0xd7, 0x42, 0xc2, 0x52, 0x49, 0x60, 0x4c, 0xd2, 0xc6,
	0x2d, 0x1a, 0x25, 0x56, 0x0c, 0x74, 0xdb, 0xbc, 0x80, 0x3a, 0x70, 0x82, 0x80, 0xae, 0x17, 0x45,
	0x81, 0x0a, 0x63, 0x71, 0x6c, 0x13, 0x95, 0x48, 0x76, 0x86, 0x6a, 0x6d, 0xa0, 0x40, 0xd7, 0xdd,
	0xf6, 0x27, 0xda, 0x2f, 0xeb, 0x77, 0x14, 0xf3, 0x20, 0x4d, 0x4a, 0xa4, 0x2c, 0x79, 0xd5, 0x55,
	0x72, 0x67, 0xce, 0x3d, 0xf7, 0x39, 0xc7, 0x14, 0xf4, 0x23, 0x1e, 0xc6, 0xe1, 0x73, 0x3a, 0x1e,
	0x87, 0xb3, 0x20, 0x4e, 0xfe, 0x1d, 0xa8, 0x53, 0xec, 0x9d, 0x87, 0x83, 0xa9, 0x3f, 0xe6, 0xe1,
	0x80, 0x46, 0xfe, 0xc0, 0xdc, 0x91, 0x57, 0xd0, 0x39, 0xf6, 0xcf, 0x83, 0x59, 0xe4, 0xb2, 0x5f,
	0x66, 0x4c, 0xc4, 0xd8, 0x83, 0x06, 0x9b, 0x52, 0x7f, 0x62, 0x57, 0x76, 0x2b, 0x7b, 0x96, 0xab,
	0x0d, 0x74, 0xa0, 0x1d, 0x51, 0x21, 0x7e, 0x0b, 0xb9, 0x67, 0x57, 0xd5, 0x45, 0x6a, 0x93, 0x7f,
	0x2a, 0xd0, 0x4d, 0x38, 0x44, 0x14, 0x06, 0x82, 0xe1, 0x00, 0xea, 0x33, 0xc1, 0xb8, 0xe2, 0xd8,
	0x1c, 0x3a, 0x83, 0xa2, 0xd0, 0x83, 0x13, 0xc1, 0xb8, 0xab, 0x70, 0xb8, 0x0f, 0x8d, 0x38, 0xfc,
	0x99, 0x05, 0x8a, 0x7b, 0x73, 0xd8, 0x2f, 0x76, 0xf8, 0x5e, 0x42, 0x5c, 0x8d, 0xc4, 0x97, 0xd0,
	0x14, 0x6c, 0xcc, 0x59, 0x6c, 0xd7, 0x6e, 0xf6, 0x31, 0x50, 0xf2, 0x2d, 0x6c, 0x1d, 0x85, 0xe7,
	0x7e, 0x70, 0xfb, 0x62, 0xff, 0xae, 0x40, 0xc7, 0x50, 0xfc, 0xcf, 0x6b, 0x7d, 0x0f, 0xf5, 0x4f,
	0x13, 0x1a, 0x60, 0x17, 0xaa, 0xbe, 0x67, 0x0a, 0xac, 0xfa, 0x1e, 0xde, 0x83, 0x26, 0x9d, 0x4a,
	0xbc, 0x4a, 0xa0, 0xe6, 0x1a, 0x4b, 0x56, 0xed, 0x07, 0x31, 0xe3, 0xbf, 0xd2, 0x89, 0x0a, 0x63,
	0xb9, 0xa9, 0x4d, 0x3e, 0xc2, 0xd6, 0xf1, 0xec, 0x54, 0x8c, 0xb9, 0x1f, 0xc5, 0x7e, 0xb8, 0xc8,
	0x39, 0x80, 0x7a, 0x34, 0xa1, 0x49, 0x49, 0x25, 0x3d, 0x90, 0xd9, 0xb8, 0x0a, 0x47, 0xbe, 0x81,
	0x86, 0x4a, 0x56, 0x0e, 0x40, 0x37, 0xc3, 0x0c, 0x40, 0xd7, 0x6b, 0x43, 0x8b, 0x5d, 0x46, 0x3e,
	0x67, 0xc2, 0xe4, 0x98, 0x98, 0xe4, 0xdf, 0x2a, 0xd4, 0x65, 0x2f, 0x17, 0x32, 0xb0, 0xa1, 0x35,
	0xe6, 0x8c, 0xc6, 0xcc, 0x4b, 0x5c, 0x8c, 0x29, 0x6f, 0x66, 0x91, 0xa7, 0x6e, 0x6a, 0xfa, 0xc6,
	0x98, 0xf8, 0x10, 0xe0, 0xcc, 0xe7, 0x22, 0x1e, 0x05, 0x74, 0xca, 0xec, 0xba, 0xe2, 0xb2, 0xd4,
	0xc9, 0x47, 0x3a, 0x65, 0xd8, 0x07, 0x6b, 0x42, 0x93, 0xdb, 0x86, 0xee, 0x88, 0x3c, 0x50, 0x97,
	0xe9, 0xe6, 0x34, 0xe7, 0x36, 0x47, 0xce, 0x58, 0x79, 0xb4, 0xb4, 0x47, 0x62, 0xe3, 0x11, 0xdc,
	0x89, 0xe8, 0xd5, 0x94, 0x05, 0xf1, 0x68, 0xca, 0xe2, 0x8b, 0xd0, 0x13, 0x76, 0x7b, 0xb7, 0xb6,
	0xb7, 0x39, 0x7c, 0x5c, 0xd2, 0x2e, 0x0d, 0xfe, 0xa0, 0xb0, 0x6e, 0x37, 0xca, 0x9a, 0x02, 0xbf,
	0x83, 0x8e, 0xc8, 0x4c, 0x44, 0xd8, 0x96, 0xe2, 0x22, 0xc5, 0x5c, 0xd9, 0xe1, 0xb9, 0x79, 0x47,
	0x59, 0x09, 0x0f, 0x27, 0x4c, 0xd8, 0xb0, 0x5b, 0x93, 0x95, 0x28, 0x83, 0x6c, 0xc3, 0x1d, 0x97,
	0x51, 0x4f, 0xed, 0xad, 0x7e, 0x2c, 0xe4, 0x35, 0xdc, 0xbd, 0x3e, 0xba, 0xdd, 0xf2, 0x93, 0x37,
	0xb0, 0x7d, 0xa2, 0xba, 0x9f, 0x21, 0x5e, 0x9b, 0xe4, 0x2d, 0x60, 0x96, 0xe4, 0x96, 0xa9, 0xec,
	0xc0, 0xf6, 0x5b, 0x36, 0x61, 0xb9, 0x54, 0x48, 0x0f, 0x30, 0x7b, 0xa8, 0xa9, 0xc9, 0x9f, 0x55,
	0xe8, 0xe4, 0xc6, 0xb1, 0xc6, 0xfa, 0xdd, 0x87, 0x96, 0x0c, 0x37, 0xf2, 0x3d, 0xf3, 0xaa, 0x9a,
	0xd2, 0x3c, 0xf4, 0x10, 0xa1, 0x1e, 0x5f, 0x45, 0xc9, 0xde, 0xa9, 0xff, 0xcb, 0x8d, 0x1c, 0x53,
	0xee, 0x8d, 0x4e, 0x39, 0x0d, 0x3c, 0xb3, 0x73, 0x96, 0x3c, 0x79, 0x2d, 0x0f, 0xf0, 0x09, 0x74,
	0xd5, 0x35, 0xbb, 0x8c, 0x46, 0xd3, 0x30, 0x88, 0x2f, 0xcc, 0xf6, 0x6d, 0xc9, 0xd3, 0x77, 0x97,
	0xd1, 0x07, 0x79, 0x86, 0x04, 0x3a, 0x29, 0xea, 0x8a, 0x51, 0x6e, 0x36, 0x71, 0xd3, 0x80, 0x7e,
	0x60, 0x94, 0xe3, 0x23, 0x50, 0xe6, 0x48, 0x2d, 0xf8, 0x81, 0xdd, 0xbe, 0x8e, 0x74, 0x44, 0x45,
	0x7c, 0x20, 0xeb, 0xf1, 0xd8, 0x19, 0x9d, 0x4d, 0x62, 0xdb, 0xda, 0xad, 0xec, 0xb5, 0xdd, 0xc4,
	0x24, 0x5f, 0x83, 0xf3, 0x46, 0x95, 0x96, 0xdf, 0x4f, 0x33, 0xca, 0xb9, 0xbe, 0x48, 0xb4, 0xee,
	0xe7, 0x4a, 0x68, 0x1f, 0xfa, 0x85, 0xdc, 0x66, 0xc2, 0xef, 0xa1, 0x9b, 0x7f, 0x41, 0x66, 0xd6,
	0x2b, 0x3d, 0xa0, 0x4e, 0xee, 0x01, 0x91, 0x87, 0xd0, 0x2f, 0x4c, 0xcc, 0x4c, 0xfc, 0x19, 0xec,
	0xb8, 0xec, 0x8c, 0x33, 0x71, 0xa1, 0x45, 0xd5, 0x24, 0x7c, 0x2f, 0x15, 0x62, 0x9d, 0x74, 0xa2,
	0xb5, 0x87, 0xd0, 0xcb, 0xc3, 0x4d, 0xc6, 0xfb, 0x59, 0x79, 0x5b, 0x49, 0xeb, 0xc9, 0x33, 0x99,
	0x98, 0x6a, 0xf5, 0x4a, 0x2d, 0x7b, 0x04, 0x0f, 0x8a, 0xe1, 0xa6, 0x90, 0x03, 0xf8, 0x4c, 0xb7,
	0x34, 0x27, 0x01, 0x86, 0xec, 0x3e, 0xb4, 0xa4, 0x1c, 0x8f, 0x52, 0xc6, 0xa6, 0x34, 0x0f, 0x3d,
	0xf2, 0x20, 0x19, 0x72, 0xde, 0xcb, 0x70, 0x22, 0xdc, 0x3d, 0xf2, 0x45, 0x2c, 0xf5, 0x5c, 0x24,
	0x0f, 0xe7, 0x1d, 0x6c, 0x67, 0xce, 0x4c, 0xf9, 0x2f, 0xa0, 0x21, 0x09, 0x85, 0x5d, 0x51, 0xe2,
	0xb4, 0xec, 0xef, 0x82, 0x06, 0x0e, 0xff, 0xb2, 0xa0, 0xf5, 0x4a, 0x9f, 0xe3, 0x8f, 0xd0, 0x4e,
	0xf4, 0x06, 0x3f, 0x2f, 0x76, 0x9d, 0x93, 0x28, 0xe7, 0x8b, 0x9b, 0x60, 0xa6, 0x82, 0x0d, 0xa4,
	0x00, 0xd7, 0x1a, 0x82, 0x4f, 0x4b, 0xd4, 0x62, 0x5e, 0xaa, 0x9c, 0xbd, 0x9b, 0x81, 0xd9, 0x10,
	0xd7, 0x5a, 0x52, 0x16, 0x62, 0x41, 0x82, 0xca, 0x42, 0x14, 0xc8, 0xd2, 0x06, 0xfe, 0x04, 0x56,
	0xda, 0x75, 0x2c, 0x29, 0x7e, 0x7e, 0x54, 0xce, 0xd3, 0x1b, 0x71, 0x29, 0xff, 0x15, 0xe0, 0xe2,
	0x1e, 0xe0, 0xf3, 0x62, 0x82, 0xd2, 0x3d, 0x73, 0x5e, 0xac, 0xee, 0x90, 0x86, 0xfe, 0x1d, 0x76,
	0x0a, 0xb4, 0x00, 0x97, 0x52, 0x15, 0xbd, 0x18, 0x67, 0x7f, 0x0d, 0x8f, 0x6c, 0xf4, 0x02, 0x79,
	0x28, 0x8b, 0x5e, 0x2e, 0x71, 0x65, 0xd1, 0x97, 0x69, 0xcf, 0x06, 0xfe, 0x01, 0xbd, 0xa2, 0x47,
	0x8d, 0xa5, 0x64, 0xa5, 0x7a, 0xe1, 0x0c, 0xd7, 0x71, 0x49, 0x13, 0x38, 0x86, 0xa6, 0xfe, 0xa2,
	0xc7, 0x12, 0x6d, 0xcd, 0xfd, 0x66, 0x70, 0x9e, 0x2c, 0x07, 0x19, 0x35, 0xf8, 0x04, 0x0d, 0xf5,
	0xe5, 0x8c, 0x25, 0x1f, 0x29, 0xd9, 0x2f, 0x73, 0xe7, 0xf1, 0x52, 0x8c, 0x61, 0x64, 0xb0, 0x95,
	0x95, 0x5d, 0xfc, 0xb2, 0xec, 0xf9, 0x2f, 0x28, 0xb9, 0xf3, 0xd5, 0x2a, 0x50, 0x1d, 0xe6, 0xb4,
	0xa9, 0x7e, 0x40, 0xbd, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x73, 0x30, 0x0f, 0xfa, 0x5f, 0x0d,
	0x00, 0x00,
}
