// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/barrel/barrel.proto

package go_micro_srv_barrel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Barrel service

type BarrelService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Barrel_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Barrel_PingPongService, error)
}

type barrelService struct {
	c    client.Client
	name string
}

func NewBarrelService(name string, c client.Client) BarrelService {
	return &barrelService{
		c:    c,
		name: name,
	}
}

func (c *barrelService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Barrel.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *barrelService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Barrel_StreamService, error) {
	req := c.c.NewRequest(c.name, "Barrel.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &barrelServiceStream{stream}, nil
}

type Barrel_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type barrelServiceStream struct {
	stream client.Stream
}

func (x *barrelServiceStream) Close() error {
	return x.stream.Close()
}

func (x *barrelServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *barrelServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *barrelServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *barrelServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *barrelService) PingPong(ctx context.Context, opts ...client.CallOption) (Barrel_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Barrel.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &barrelServicePingPong{stream}, nil
}

type Barrel_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type barrelServicePingPong struct {
	stream client.Stream
}

func (x *barrelServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *barrelServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *barrelServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *barrelServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *barrelServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *barrelServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Barrel service

type BarrelHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Barrel_StreamStream) error
	PingPong(context.Context, Barrel_PingPongStream) error
}

func RegisterBarrelHandler(s server.Server, hdlr BarrelHandler, opts ...server.HandlerOption) error {
	type barrel interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Barrel struct {
		barrel
	}
	h := &barrelHandler{hdlr}
	return s.Handle(s.NewHandler(&Barrel{h}, opts...))
}

type barrelHandler struct {
	BarrelHandler
}

func (h *barrelHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.BarrelHandler.Call(ctx, in, out)
}

func (h *barrelHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.BarrelHandler.Stream(ctx, m, &barrelStreamStream{stream})
}

type Barrel_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type barrelStreamStream struct {
	stream server.Stream
}

func (x *barrelStreamStream) Close() error {
	return x.stream.Close()
}

func (x *barrelStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *barrelStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *barrelStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *barrelStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *barrelHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.BarrelHandler.PingPong(ctx, &barrelPingPongStream{stream})
}

type Barrel_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type barrelPingPongStream struct {
	stream server.Stream
}

func (x *barrelPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *barrelPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *barrelPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *barrelPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *barrelPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *barrelPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
